#!/usr/bin/env bash
# Shared boot wrapper for the two BAR1 host steps (s11, s12).
#
# The recipe is 04_BETRIEB.md of the P2P handover, unchanged. It is GENERATED
# into the run directory rather than pasted into two step scripts, so that
#
#   * the two arms of s12 differ in EXACTLY the three SGLANG_HTCCL* lines and
#     in nothing else -- which is the whole point of the comparison, and the
#     one thing a hand-copied second command would eventually get wrong,
#   * the script that actually ran is an artifact next to its result.
#
# Three properties of the recipe are load-bearing and easy to lose:
#   * CUDA_HOME is MANDATORY. Without it the JIT build fails on ninja.
#   * NO CUDA_DEVICE_ORDER. cuda:0 is the 5090 in this recipe, and the
#     --rank-auto-reserve-mib values are written for that order. Setting
#     PCI_BUS_ID silently renumbers the cards and the reserves land wrong.
#   * --rank-auto-reserve-mib 3000,2700,2700. 2700 on the 3080s is the proven
#     floor; 2200 survives the warmup and dies in the first real prefill.
#
# NOT executable on its own.

set -uo pipefail

# bar1_write_boot_script <container path> <arm> <host log> <host pidfile> <port>
#
# arm = "bar1"       the three SGLANG_HTCCL* lines plus the driver header source
#       "grundlinie" none of them, everything else byte-identical
bar1_write_boot_script() {
    local out="$1" arm="$2" hostlog="$3" hostpid="$4" port="$5"
    local hv hw hn hm hcache
    hv="$(host_path "$VENV")" || return 2
    hw="$(host_path "${BAR1_HOST_WT:-$WT}")" || return 2
    hn="$(host_path "$BAR1_NV_SOURCE")" || return 2
    hm="$(host_path "$MODEL_ROOT/Qwen3.6-27B-FP8")" || return 2
    hcache="$(host_path "$BAR1_EXTCACHE")" || return 2

    # The ONE difference between the arms, and it is an array literal rather
    # than a spliced-in line: an empty line inside a backslash continuation
    # would end the command early and boot the baseline recipe with a truncated
    # argument list.
    local htccl_env="HTCCL_ENV=()"
    if [ "$arm" = "bar1" ]; then
        htccl_env="HTCCL_ENV=(SGLANG_HTCCL=1 SGLANG_HTCCL_TRANSPORT=bar1"
        htccl_env="$htccl_env SGLANG_HTCCL_GRAPH_FREIGABE=1"
        htccl_env="$htccl_env SGLANG_HTCCL_BAR1_NV_QUELLE=$hn)"
    fi

    cat > "$out" <<EOF
#!/usr/bin/env bash
# GENERATED by _bar1_host_boot.sh -- arm "$arm". Runs on the PVE host.
set -uo pipefail
mkdir -p "$BAR1_HOST_LOGDIR"
rm -f "$hostpid"
cd $hw
$htccl_env
PYTHONPATH=$hw/python:$hv/lib/python3.12/site-packages \\
LD_LIBRARY_PATH=$hv/lib/python3.12/site-packages/nvidia/cu13/lib \\
CUDA_HOME=$hv/lib/python3.12/site-packages/nvidia/cu13 \\
SGLANG_UNEVEN_DCP=1 SGLANG_UNEVEN_DCP_WEIGHTED=1 \\
SGLANG_MAMBA_SSM_DTYPE=bfloat16 FLASHINFER_DISABLE_VERSION_CHECK=1 \\
TORCH_EXTENSIONS_DIR=$hcache \\
TORCH_CUDA_ARCH_LIST="8.6;12.0" MAX_JOBS=4 \\
setsid env \${HTCCL_ENV[@]+"\${HTCCL_ENV[@]}"} \\
  /spinning/miniforge3_local_install/bin/python3.12 -m sglang.launch_server \\
  --model-path $hm \\
  --tp-size 3 --rank-gpu-id 0,1,2 --rank-tp-ratio auto-performance \\
  --rank-auto-reserve-mib 3000,2700,2700 \\
  --kv-cache-dtype fp8_e4m3 --context-length 32768 --trust-remote-code \\
  --max-running-requests 16 \\
  --speculative-algorithm NEXTN --speculative-num-steps 3 \\
  --speculative-eagle-topk 1 --speculative-num-draft-tokens 4 \\
  --enable-metrics --host 127.0.0.1 --port $port \\
  > "$hostlog" 2>&1 &
echo \$! > "$hostpid"
echo "gestartet, pid \$(cat "$hostpid")"
EOF
    chmod +x "$out"
    return 0
}

# bar1_boot_start <container path of boot script> -> echoes the host pid
bar1_boot_start() {
    local script="$1" hostpid="$2" pid
    host_run_script 180 "$script" || return 1
    pid="$(host_ssh_for 60 "cat $hostpid 2>/dev/null")"
    pid="${pid//[^0-9]/}"
    if [ -z "$pid" ]; then
        echo "kein Host-pid in $hostpid" >&2
        return 1
    fi
    printf '%s\n' "$pid"
    return 0
}

# The BAR1 code has to BE in the worktree under test. Without this check a step
# would boot the plain transport, log nothing about bar1, and the check would
# report a coverage gap that is really a wrong checkout.
bar1_require_integration() {
    local wt="${BAR1_HOST_WT:-$WT}" missing=""
    local f
    for f in \
        "python/sglang/srt/distributed/device_communicators/htccl_bar1.py" \
        "benchmark/bar1_graph_check.py"
    do
        [ -f "$wt/$f" ] || missing="$missing $f"
    done
    if [ -n "$missing" ]; then
        echo "STOP: BAR1-Integration fehlt in $wt --$missing" >&2
        echo "BAR1_HOST_WT auf den Arbeitsbaum mit der BAR1-Integration setzen." >&2
        if [ -n "${BATTERY_STEP_DIR:-}" ]; then
            printf 'fehlt in %s:%s\n' "$wt" "$missing" \
                > "$BATTERY_STEP_DIR/integration_missing.txt"
        fi
        return 2
    fi
    return 0
}
