#!/usr/bin/env bash
# Shared boot wrapper for the two BAR1 host steps (s11, s12).
#
# The recipe is 04_BETRIEB.md of the P2P handover, unchanged. It is GENERATED
# into the run directory rather than pasted into two step scripts, so that
#
#   * the two arms of s12 differ in EXACTLY the three SGLANG_BARLINK* lines and
#     in nothing else -- which is the whole point of the comparison, and the
#     one thing a hand-copied second command would eventually get wrong,
#   * the script that actually ran is an artifact next to its result.
#
# Three properties of the recipe are load-bearing and easy to lose:
#   * CUDA_HOME is MANDATORY. Without it the JIT build fails on ninja.
#   * NO CUDA_DEVICE_ORDER. cuda:0 is the 5090 in this recipe, and the
#     --rank-auto-reserve-mib values are written for that order. Setting
#     PCI_BUS_ID silently renumbers the cards and the reserves land wrong.
#   * --rank-auto-reserve-mib 3000,2700,2700. 2700 on the 3080s is the proven
#     floor; 2200 survives the warmup and dies in the first real prefill.
#
# NOT executable on its own.

set -uo pipefail

# bar1_write_boot_script <container path> <arm> <host log> <host pidfile> <port>
#
# arm = "bar1"       the three SGLANG_BARLINK* lines plus the driver header source
#       "grundlinie" none of them, everything else byte-identical
bar1_write_boot_script() {
    local out="$1" arm="$2" hostlog="$3" hostpid="$4" port="$5"
    local hv hw hn hm hcache
    hv="$(host_path "$VENV")" || return 2
    hw="$(host_path "${BAR1_HOST_WT:-$WT}")" || return 2
    hn="$(host_path "$BAR1_NV_SOURCE")" || return 2
    hm="$(host_path "$MODEL_ROOT/Qwen3.6-27B-FP8")" || return 2
    hcache="$(host_path "$BAR1_EXTCACHE")" || return 2

    # The ONE difference between the arms, and it is an array literal rather
    # than a spliced-in line: an empty line inside a backslash continuation
    # would end the command early and boot the baseline recipe with a truncated
    # argument list.
    #
    # `arm` decides the TRANSPORT and nothing else. Anything a caller wants on
    # top of that -- further SGLANG_* variables, further server arguments --
    # comes through the two optional variables below and lands in the same two
    # array literals, for the same reason: an array that expands to nothing
    # when empty leaves the recipe byte-identical for callers that do not set
    # it (s11, s12), while a spliced-in line would have to be conditionally
    # present and would eventually be spliced in wrong.
    #
    #   BAR1_EXTRA_ENV   space separated VAR=VAL, prepended to the server env
    #   BAR1_EXTRA_ARGS  space separated server arguments, appended to the
    #                    launch command
    local barlink_env="BARLINK_ENV=()"
    if [ "$arm" = "bar1" ]; then
        barlink_env="BARLINK_ENV=(SGLANG_BARLINK=1 SGLANG_BARLINK_TRANSPORT=bar1"
        barlink_env="$barlink_env SGLANG_BARLINK_GRAPH_ENABLE=1"
        barlink_env="$barlink_env SGLANG_BARLINK_BAR1_NV_SOURCE=$hn)"
    fi
    if [ -n "${BAR1_EXTRA_ENV:-}" ]; then
        barlink_env="${barlink_env%)} ${BAR1_EXTRA_ENV})"
        # The baseline arm's literal is "BARLINK_ENV=()" -- stripping the ")"
        # above leaves "BARLINK_ENV=(", so the extras become the whole array.
    fi
    local extra_args="EXTRA_ARGS=(${BAR1_EXTRA_ARGS:-})"

    cat > "$out" <<EOF
#!/usr/bin/env bash
# GENERATED by _bar1_host_boot.sh -- arm "$arm". Runs on the PVE host.
set -uo pipefail
mkdir -p "$BAR1_HOST_LOGDIR"
rm -f "$hostpid"
cd $hw
$barlink_env
$extra_args
PYTHONPATH=$hw/python:$hv/lib/python3.12/site-packages \\
LD_LIBRARY_PATH=$hv/lib/python3.12/site-packages/nvidia/cu13/lib \\
CUDA_HOME=$hv/lib/python3.12/site-packages/nvidia/cu13 \\
SGLANG_UNEVEN_DCP=1 SGLANG_UNEVEN_DCP_WEIGHTED=1 \\
SGLANG_MAMBA_SSM_DTYPE=bfloat16 FLASHINFER_DISABLE_VERSION_CHECK=1 \\
TORCH_EXTENSIONS_DIR=$hcache \\
TORCH_CUDA_ARCH_LIST="8.6;12.0" MAX_JOBS=4 \\
setsid env \${BARLINK_ENV[@]+"\${BARLINK_ENV[@]}"} \\
  /spinning/miniforge3_local_install/bin/python3.12 -m sglang.launch_server \\
  --model-path $hm \\
  --tp-size 3 --rank-gpu-id 0,1,2 --rank-tp-ratio auto-performance \\
  --rank-auto-reserve-mib 3000,2700,2700 \\
  --kv-cache-dtype fp8_e4m3 --context-length 32768 --trust-remote-code \\
  --max-running-requests 16 \\
  --speculative-algorithm NEXTN --speculative-num-steps 3 \\
  --speculative-eagle-topk 1 --speculative-num-draft-tokens 4 \\
  --enable-metrics --host 127.0.0.1 --port $port \\
  \${EXTRA_ARGS[@]+"\${EXTRA_ARGS[@]}"} \\
  > "$hostlog" 2>&1 &
echo \$! > "$hostpid"
echo "gestartet, pid \$(cat "$hostpid")"
EOF
    chmod +x "$out"
    return 0
}

# bar1_boot_start <container path of boot script> -> echoes the host pid
# bar1_pid_ok <string> -- true only for a plain positive integer.
#
# It exists because a "pid" that is none does not stand out in `kill`, it
# slips through: `kill -0 gestartet, pid 1962637` fails the same way a dead
# process does, and the cleanup path took that for "nothing to do".
bar1_pid_ok() {
    case "${1:-}" in
        ''|*[!0-9]*) return 1 ;;
        0) return 1 ;;
        *) return 0 ;;
    esac
}

# bar1_boot_start <container path of boot script> <host pidfile> -> pid on stdout
#
# THE REDIRECTION TO STDERR IS THE POINT, not cosmetics. `host_run_script`
# passes the remote script's output through, and the boot script says
# "gestartet, pid <n>" as its last word. The caller reads this function by
# command substitution -- so BOTH ended up in the variable:
#
#     SERVER_PID='gestartet, pid 1962637
#     1962637'
#
# That is not a guess; it is exactly what host_pids of the 2026-07-30 run
# holds (31 bytes, two lines). The consequences went far beyond an ugly
# value: `host_dump_and_kill` asked `kill -0 <that salad>`, got an error and
# took its early exit "there is nothing there, so nothing to kill". The
# server survived EVERY exit the script had -- cleanup at the end, the EXIT
# trap, all of them -- held the three cards along with their dmabuf
# attachments, and the next attempt ran against it: its graph gate got ENOMEM
# from the holder, and its smoke was answered by the server of the PREVIOUS
# attempt.
#
# Same family as the r7c finding "load_card_order through a pipe": a function
# that returns its value on stdout must not let anything else onto stdout. It
# costs one `>&2`.
bar1_boot_start() {
    local script="$1" hostpid="$2" pid
    host_run_script 180 "$script" >&2 || return 1
    pid="$(host_ssh_for 60 "cat $hostpid 2>/dev/null")"
    pid="${pid//[^0-9]/}"
    if ! bar1_pid_ok "$pid"; then
        echo "kein brauchbarer Host-pid in $hostpid (read: '$pid')" >&2
        return 1
    fi
    printf '%s\n' "$pid"
    return 0
}

# bar1_altlast_pruefen <port> -- is anything from the previous attempt still
# running?
#
# ONE ssh round trip, three questions, no side effect: this test kills
# nothing. It only names what it finds, and the caller aborts. Why it does not
# clean up: whatever runs on those cards need not be ours (a foreign session),
# and a broad `pkill python` would be exactly the blast radius the rig rules
# rule out. A named abort is a finding; a run against a zombie is wrong
# numbers.
#
# Three tripwires, because each one alone is blind:
#   * the port says nothing about processes that have already crashed and are
#     holding the cards anyway,
#   * the process list says nothing about a server running under a different
#     name,
#   * the card occupancy does not care who holds it -- and that is exactly the
#     condition building the BAR1 region really depends on (the holder
#     reported ENOMEM).
BAR1_ALTLAST_MIB="${BAR1_ALTLAST_MIB:-2000}"
bar1_altlast_pruefen() {
    local port="$1" report="${2:-}" raw busy proc vram bad=""
    # A report from an EARLIER, failed attempt in the same step directory must
    # not survive into a run that is now clean. That is exactly what happened
    # on 2026-07-30: attempt 5 wrote "Altlast:launch_server-Prozesse=4" here
    # (real processes of a previous attempt, still dying at the time), ten
    # minutes later attempt 6 ran fully green -- but compose() read the same
    # report, never cleared, and devalued the green run with a finding that
    # belonged to an attempt long since finished. A run's verdict comes out of
    # ITS OWN artifacts, never out of a remnant of another one. Clear first,
    # then check; the report below is only written again if THIS run finds
    # something itself.
    [ -n "$report" ] && rm -f "$report"
    raw="$(host_ssh_for 90 "
        echo \"PORT=\$( (ss -ltn 2>/dev/null || netstat -ltn 2>/dev/null) \
                        | grep -c ':$port ' )\";
        echo \"PROC=\$(pgrep -c -f '[s]glang.launch_server' 2>/dev/null || echo 0)\";
        # Bracket idiom [s]glang instead of the plain name: pgrep -f matches
        # against the full command line, and our own ssh session carries the
        # search pattern as text (this embedded heredoc). Without the bracket
        # the check counts itself and reports leftover processes on an empty
        # host.
        echo \"VRAM=\$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits \
                       2>/dev/null | tr '\n' ',')\";
    " 2>/dev/null)" || {
        echo "STOP: leftover check not possible (host not reachable)" >&2
        return 2
    }
    busy="$(printf '%s\n' "$raw" | sed -n 's/^PORT=//p' | tail -1)"
    proc="$(printf '%s\n' "$raw" | sed -n 's/^PROC=//p' | tail -1)"
    vram="$(printf '%s\n' "$raw" | sed -n 's/^VRAM=//p' | tail -1)"
    [ -n "$busy" ] || busy=0
    [ -n "$proc" ] || proc=0

    [ "$busy" -gt 0 ] 2>/dev/null && bad="$bad Port-$port-belegt"
    [ "$proc" -gt 0 ] 2>/dev/null && bad="$bad launch_server-Prozesse=$proc"
    local i=0 mib
    local IFS=,
    for mib in $vram; do
        mib="${mib// /}"
        [ -z "$mib" ] && continue
        if [ "$mib" -gt "$BAR1_ALTLAST_MIB" ] 2>/dev/null; then
            bad="$bad GPU$i=${mib}MiB"
        fi
        i=$((i + 1))
    done
    unset IFS

    if [ -n "$bad" ]; then
        echo "STOP: Altlast von einem vorherigen Anlauf --$bad" >&2
        echo "The cards or the port are not free. A run against that measures" >&2
        echo "the old server, not this one. Clean up first (only OUR OWN pids" >&2
        echo "from host_pids), then start again." >&2
        [ -n "$report" ] && printf 'Altlast:%s\n' "$bad" > "$report"
        return 1
    fi
    echo "leftover check: port free, no launch_server processes, cards below ${BAR1_ALTLAST_MIB} MiB"
    return 0
}

# bar1_kill_host_server <pid or empty> <host pidfile> <dump path>
#
# The cleanup path, and it has TWO sources for the pid. The caller's variable
# is the first; if the script dies between boot and assignment it is empty
# while a server has long been running on the host -- then the pidfile the
# boot script wrote itself applies. Without the second source that very window
# is a leak.
BAR1_KILL_NACHSCHAU_TIMEOUT_S="${BAR1_KILL_NACHSCHAU_TIMEOUT_S:-15}"
BAR1_KILL_NACHSCHAU_POLL_S="${BAR1_KILL_NACHSCHAU_POLL_S:-1}"
bar1_kill_host_server() {
    local pid="${1:-}" hostpid="${2:-}" dump="${3:-}" file_pid=""
    if ! bar1_pid_ok "$pid" && [ -n "$hostpid" ]; then
        file_pid="$(host_ssh_for 60 "cat $hostpid 2>/dev/null")" || file_pid=""
        file_pid="${file_pid//[^0-9]/}"
        bar1_pid_ok "$file_pid" && pid="$file_pid"
    fi
    bar1_pid_ok "$pid" || return 0
    host_dump_and_kill "$pid" "${dump:-/dev/null}"
    # LOOK AFTERWARDS, bounded. A kill nobody verifies is an intention -- but
    # an IMMEDIATE, one-shot look is blind to the normal span between SIGTERM
    # and the actual disappearance from the process list. That lag was the
    # cause when a still-dying server (no longer alive, just not yet
    # deregistered) left the next attempt hanging at its leftover check: the
    # look judged "still alive" straight away, without giving the normal exit
    # time a chance. Bounded waiting instead of judging on the spot -- if the
    # process dies within the deadline it counts as cleaned up; if it does
    # NOT, the honest report "still alive" stands (and the caller has never
    # treated that as a STOP for the run).
    local tries=$(( BAR1_KILL_NACHSCHAU_TIMEOUT_S / BAR1_KILL_NACHSCHAU_POLL_S ))
    [ "$tries" -lt 1 ] && tries=1
    local i=0
    while host_ssh_for 60 "kill -0 $pid 2>/dev/null" >/dev/null 2>&1; do
        i=$((i + 1))
        if [ "$i" -ge "$tries" ]; then
            echo "WARNING: host pid $pid lebt nach dem Abraeumen noch (after ~${BAR1_KILL_NACHSCHAU_TIMEOUT_S}s grace period)." >&2
            echo "The next attempt will hang at the leftover check." >&2
            return 1
        fi
        sleep "$BAR1_KILL_NACHSCHAU_POLL_S"
    done
    echo "host server $pid abgeraeumt."
    return 0
}

# The BAR1 code has to BE in the worktree under test. Without this check a step
# would boot the plain transport, log nothing about bar1, and the check would
# report a coverage gap that is really a wrong checkout.
bar1_require_integration() {
    local wt="${BAR1_HOST_WT:-$WT}" missing=""
    local f
    for f in \
        "python/sglang/srt/distributed/device_communicators/barlink_bar1.py" \
        "benchmark/bar1_graph_check.py"
    do
        [ -f "$wt/$f" ] || missing="$missing $f"
    done
    if [ -n "$missing" ]; then
        echo "STOP: BAR1 integration missing in $wt --$missing" >&2
        echo "Point BAR1_HOST_WT at the worktree that has the BAR1 integration." >&2
        if [ -n "${BATTERY_STEP_DIR:-}" ]; then
            printf 'missing in %s:%s\n' "$wt" "$missing" \
                > "$BATTERY_STEP_DIR/integration_missing.txt"
        fi
        return 2
    fi
    return 0
}
