#!/usr/bin/env bash
# Shared boot wrapper for the two BAR1 host steps (s11, s12).
#
# The recipe is 04_BETRIEB.md of the P2P handover, unchanged. It is GENERATED
# into the run directory rather than pasted into two step scripts, so that
#
#   * the two arms of s12 differ in EXACTLY the three SGLANG_HTCCL* lines and
#     in nothing else -- which is the whole point of the comparison, and the
#     one thing a hand-copied second command would eventually get wrong,
#   * the script that actually ran is an artifact next to its result.
#
# Three properties of the recipe are load-bearing and easy to lose:
#   * CUDA_HOME is MANDATORY. Without it the JIT build fails on ninja.
#   * NO CUDA_DEVICE_ORDER. cuda:0 is the 5090 in this recipe, and the
#     --rank-auto-reserve-mib values are written for that order. Setting
#     PCI_BUS_ID silently renumbers the cards and the reserves land wrong.
#   * --rank-auto-reserve-mib 3000,2700,2700. 2700 on the 3080s is the proven
#     floor; 2200 survives the warmup and dies in the first real prefill.
#
# NOT executable on its own.

set -uo pipefail

# bar1_write_boot_script <container path> <arm> <host log> <host pidfile> <port>
#
# arm = "bar1"       the three SGLANG_HTCCL* lines plus the driver header source
#       "grundlinie" none of them, everything else byte-identical
bar1_write_boot_script() {
    local out="$1" arm="$2" hostlog="$3" hostpid="$4" port="$5"
    local hv hw hn hm hcache
    hv="$(host_path "$VENV")" || return 2
    hw="$(host_path "${BAR1_HOST_WT:-$WT}")" || return 2
    hn="$(host_path "$BAR1_NV_SOURCE")" || return 2
    hm="$(host_path "$MODEL_ROOT/Qwen3.6-27B-FP8")" || return 2
    hcache="$(host_path "$BAR1_EXTCACHE")" || return 2

    # The ONE difference between the arms, and it is an array literal rather
    # than a spliced-in line: an empty line inside a backslash continuation
    # would end the command early and boot the baseline recipe with a truncated
    # argument list.
    local htccl_env="HTCCL_ENV=()"
    if [ "$arm" = "bar1" ]; then
        htccl_env="HTCCL_ENV=(SGLANG_HTCCL=1 SGLANG_HTCCL_TRANSPORT=bar1"
        htccl_env="$htccl_env SGLANG_HTCCL_GRAPH_FREIGABE=1"
        htccl_env="$htccl_env SGLANG_HTCCL_BAR1_NV_QUELLE=$hn)"
    fi

    cat > "$out" <<EOF
#!/usr/bin/env bash
# GENERATED by _bar1_host_boot.sh -- arm "$arm". Runs on the PVE host.
set -uo pipefail
mkdir -p "$BAR1_HOST_LOGDIR"
rm -f "$hostpid"
cd $hw
$htccl_env
PYTHONPATH=$hw/python:$hv/lib/python3.12/site-packages \\
LD_LIBRARY_PATH=$hv/lib/python3.12/site-packages/nvidia/cu13/lib \\
CUDA_HOME=$hv/lib/python3.12/site-packages/nvidia/cu13 \\
SGLANG_UNEVEN_DCP=1 SGLANG_UNEVEN_DCP_WEIGHTED=1 \\
SGLANG_MAMBA_SSM_DTYPE=bfloat16 FLASHINFER_DISABLE_VERSION_CHECK=1 \\
TORCH_EXTENSIONS_DIR=$hcache \\
TORCH_CUDA_ARCH_LIST="8.6;12.0" MAX_JOBS=4 \\
setsid env \${HTCCL_ENV[@]+"\${HTCCL_ENV[@]}"} \\
  /spinning/miniforge3_local_install/bin/python3.12 -m sglang.launch_server \\
  --model-path $hm \\
  --tp-size 3 --rank-gpu-id 0,1,2 --rank-tp-ratio auto-performance \\
  --rank-auto-reserve-mib 3000,2700,2700 \\
  --kv-cache-dtype fp8_e4m3 --context-length 32768 --trust-remote-code \\
  --max-running-requests 16 \\
  --speculative-algorithm NEXTN --speculative-num-steps 3 \\
  --speculative-eagle-topk 1 --speculative-num-draft-tokens 4 \\
  --enable-metrics --host 127.0.0.1 --port $port \\
  > "$hostlog" 2>&1 &
echo \$! > "$hostpid"
echo "gestartet, pid \$(cat "$hostpid")"
EOF
    chmod +x "$out"
    return 0
}

# bar1_boot_start <container path of boot script> -> echoes the host pid
# bar1_pid_ok <string> -- wahr nur fuer eine schlichte positive Ganzzahl.
#
# Es gibt sie, weil ein "pid", der keiner ist, in `kill` nicht auffaellt,
# sondern durchrutscht: `kill -0 gestartet, pid 1962637` scheitert wie ein
# toter Prozess, und der Aufraeumpfad hielt das fuer "nichts zu tun".
bar1_pid_ok() {
    case "${1:-}" in
        ''|*[!0-9]*) return 1 ;;
        0) return 1 ;;
        *) return 0 ;;
    esac
}

# bar1_boot_start <container path of boot script> <host pidfile> -> pid on stdout
#
# DIE UMLEITUNG NACH STDERR IST DER PUNKT, nicht Kosmetik. `host_run_script`
# reicht die Ausgabe des entfernten Skripts durch, und das Bootskript sagt zum
# Schluss "gestartet, pid <n>". Der Aufrufer liest diese Funktion per
# Kommandosubstitution -- also landete BEIDES in der Variablen:
#
#     SERVER_PID='gestartet, pid 1962637
#     1962637'
#
# Das ist keine Vermutung; genau so steht es in host_pids des Laufs vom
# 2026-07-30 (31 Byte, zwei Zeilen). Die Folgen reichten weit ueber einen
# haesslichen Wert hinaus: `host_dump_and_kill` fragte `kill -0 <dieser
# Salat>`, bekam einen Fehler und nahm den frueher Ausstieg "da ist nichts,
# also auch nichts zu toeten". Der Server ueberlebte JEDEN Ausgang des
# Skripts -- Aufraeumen am Ende, trap auf EXIT, alles --, hielt die drei
# Karten samt dmabuf-Anhaftungen, und der naechste Anlauf lief gegen ihn:
# sein Graph-Tor bekam ENOMEM vom Halter, und sein Smoke wurde vom Server des
# VORIGEN Anlaufs beantwortet.
#
# Dieselbe Familie wie der r7c-Befund "load_card_order durch eine Pipe": eine
# Funktion, die ihren Rueckgabewert ueber stdout liefert, darf auf stdout
# nichts anderes zulassen. Es kostet ein `>&2`.
bar1_boot_start() {
    local script="$1" hostpid="$2" pid
    host_run_script 180 "$script" >&2 || return 1
    pid="$(host_ssh_for 60 "cat $hostpid 2>/dev/null")"
    pid="${pid//[^0-9]/}"
    if ! bar1_pid_ok "$pid"; then
        echo "kein brauchbarer Host-pid in $hostpid (gelesen: '$pid')" >&2
        return 1
    fi
    printf '%s\n' "$pid"
    return 0
}

# bar1_altlast_pruefen <port> -- laeuft vom vorigen Anlauf noch etwas?
#
# EIN ssh-Umlauf, drei Fragen, keine Nebenwirkung: dieser Test toetet nichts.
# Er benennt nur, was er findet, und der Aufrufer bricht ab. Warum nicht
# aufraeumen: was auf diesen Karten laeuft, muss nicht von uns sein
# (Fremdsitzung), und ein breites `pkill python` waere genau der
# Blast-Radius, den die Rig-Regeln ausschliessen. Ein benannter Abbruch ist
# ein Befund; ein Lauf gegen einen Zombie sind falsche Zahlen.
#
# Drei Tripdraehte, weil jeder allein blind ist:
#   * der Port sagt nichts ueber Prozesse, die schon abgestuerzt sind und die
#     Karten trotzdem halten,
#   * die Prozessliste sagt nichts ueber einen Server, der unter anderem
#     Namen laeuft,
#   * der Kartenbelegung ist egal, wer sie haelt -- und genau das ist die
#     Bedingung, an der der Aufbau der BAR1-Region wirklich haengt (der
#     Halter meldete ENOMEM).
BAR1_ALTLAST_MIB="${BAR1_ALTLAST_MIB:-2000}"
bar1_altlast_pruefen() {
    local port="$1" bericht="${2:-}" roh belegt proc vram schlimm=""
    roh="$(host_ssh_for 90 "
        echo \"PORT=\$( (ss -ltn 2>/dev/null || netstat -ltn 2>/dev/null) \
                        | grep -c ':$port ' )\";
        echo \"PROC=\$(pgrep -c -f '[s]glang.launch_server' 2>/dev/null || echo 0)\";
        # Bracket-Idiom [s]glang statt sglang: pgrep -f matcht gegen die volle
        # Kommandozeile, und die eigene ssh-Session traegt das Suchmuster als
        # Text (dieser hier eingebettete Heredoc). Ohne die Klammer zaehlt
        # sich die Pruefung selbst mit und meldet Alt-Prozesse auf einem
        # leeren Host.
        echo \"VRAM=\$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits \
                       2>/dev/null | tr '\n' ',')\";
    " 2>/dev/null)" || {
        echo "STOP: Altlast-Pruefung nicht durchfuehrbar (Host nicht erreichbar)" >&2
        return 2
    }
    belegt="$(printf '%s\n' "$roh" | sed -n 's/^PORT=//p' | tail -1)"
    proc="$(printf '%s\n' "$roh" | sed -n 's/^PROC=//p' | tail -1)"
    vram="$(printf '%s\n' "$roh" | sed -n 's/^VRAM=//p' | tail -1)"
    [ -n "$belegt" ] || belegt=0
    [ -n "$proc" ] || proc=0

    [ "$belegt" -gt 0 ] 2>/dev/null && schlimm="$schlimm Port-$port-belegt"
    [ "$proc" -gt 0 ] 2>/dev/null && schlimm="$schlimm launch_server-Prozesse=$proc"
    local i=0 mib
    local IFS=,
    for mib in $vram; do
        mib="${mib// /}"
        [ -z "$mib" ] && continue
        if [ "$mib" -gt "$BAR1_ALTLAST_MIB" ] 2>/dev/null; then
            schlimm="$schlimm GPU$i=${mib}MiB"
        fi
        i=$((i + 1))
    done
    unset IFS

    if [ -n "$schlimm" ]; then
        echo "STOP: Altlast von einem vorherigen Anlauf --$schlimm" >&2
        echo "Die Karten oder der Port sind nicht frei. Ein Lauf dagegen misst" >&2
        echo "den alten Server, nicht diesen. Erst aufraeumen (nur EIGENE pids" >&2
        echo "aus host_pids), dann neu starten." >&2
        [ -n "$bericht" ] && printf 'Altlast:%s\n' "$schlimm" > "$bericht"
        return 1
    fi
    echo "Altlast-Pruefung: Port frei, keine launch_server-Prozesse, Karten unter ${BAR1_ALTLAST_MIB} MiB"
    return 0
}

# bar1_kill_host_server <pid or empty> <host pidfile> <dump path>
#
# Der Aufraeumpfad, und er hat ZWEI Quellen fuer den pid. Die Variable des
# Aufrufers ist die erste; stirbt das Skript zwischen Boot und Zuweisung, ist
# sie leer, waehrend auf dem Host laengst ein Server laeuft -- dann gilt die
# Pidfile, die das Bootskript selbst geschrieben hat. Ohne die zweite Quelle
# ist genau das Zeitfenster ein Leck.
bar1_kill_host_server() {
    local pid="${1:-}" hostpid="${2:-}" dump="${3:-}" datei_pid=""
    if ! bar1_pid_ok "$pid" && [ -n "$hostpid" ]; then
        datei_pid="$(host_ssh_for 60 "cat $hostpid 2>/dev/null")" || datei_pid=""
        datei_pid="${datei_pid//[^0-9]/}"
        bar1_pid_ok "$datei_pid" && pid="$datei_pid"
    fi
    bar1_pid_ok "$pid" || return 0
    host_dump_and_kill "$pid" "${dump:-/dev/null}"
    # NACHSEHEN. Ein Kill, den niemand nachprueft, ist eine Absicht -- und die
    # Absicht war schon da, als der Server den Lauf ueberlebte.
    if host_ssh_for 60 "kill -0 $pid 2>/dev/null" >/dev/null 2>&1; then
        echo "WARNUNG: Host-pid $pid lebt nach dem Abraeumen noch." >&2
        echo "Der naechste Anlauf wird an der Altlast-Pruefung haengen bleiben." >&2
        return 1
    fi
    echo "Host-Server $pid abgeraeumt."
    return 0
}

# The BAR1 code has to BE in the worktree under test. Without this check a step
# would boot the plain transport, log nothing about bar1, and the check would
# report a coverage gap that is really a wrong checkout.
bar1_require_integration() {
    local wt="${BAR1_HOST_WT:-$WT}" missing=""
    local f
    for f in \
        "python/sglang/srt/distributed/device_communicators/htccl_bar1.py" \
        "benchmark/bar1_graph_check.py"
    do
        [ -f "$wt/$f" ] || missing="$missing $f"
    done
    if [ -n "$missing" ]; then
        echo "STOP: BAR1-Integration fehlt in $wt --$missing" >&2
        echo "BAR1_HOST_WT auf den Arbeitsbaum mit der BAR1-Integration setzen." >&2
        if [ -n "${BATTERY_STEP_DIR:-}" ]; then
            printf 'fehlt in %s:%s\n' "$wt" "$missing" \
                > "$BATTERY_STEP_DIR/integration_missing.txt"
        fi
        return 2
    fi
    return 0
}
