#!/usr/bin/env bash
# S10 -- patched driver plus preconditions for the BAR1 direct path.
#
# Runs on the PVE HOST over ssh. The container cannot do this at all: the
# holder device has major 10, which is not in CT999's device allowlist, and a
# module reload is a host operation regardless.
#
# The recipe is 04_BETRIEB.md of the P2P handover, unchanged, with one
# deliberate difference: the PCI addresses for the reset are RESOLVED at
# runtime from lspci instead of being pasted in. Enumeration shifts between
# boots and driver states, and a hardcoded bus id would reset the wrong device
# or nothing at all.
#
# The step is idempotent. When the patched module is already loaded WITH the
# regkey and the holder is up, nothing is unloaded: it verifies and records
# reload_performed=false. Churning the driver to prove it can be churned would
# cost the very state the next two steps need.
#
# Viewers: nvtop and friends hold the modules. They are only terminated with
# BAR1_VIEWER_KILL_OK=1, and the permission does NOT carry over between runs
# (05_FALLEN). Without it the step stops and names the pids.

set -uo pipefail
cd "$(dirname "$0")"
source ./battery_common.sh
source ./battery_host.sh

DIR="${BATTERY_STEP_DIR:?BATTERY_STEP_DIR fehlt -- ueber run_step.sh starten}"
HDIR_LOCAL="$DIR/host"
mkdir -p "$HDIR_LOCAL"
HDIR="$(host_path "$HDIR_LOCAL")" || exit 2
NV_HOST="$(host_path "$BAR1_NV_SOURCE")" || exit 2
HOLDER_HOST="$(host_path "$BAR1_HOLDER_KO")" || exit 2

compose() { "$PY" "$BATTERY_DIR/s10_bar1_driver.py" --step-dir "$DIR"; }

echo "== Host erreichbar? =="
if ! host_reachable; then
    echo "fehlgeschlagen" > "$HDIR_LOCAL/reach.txt"
    echo "Host $BAR1_HOST nicht erreichbar (Key $BAR1_HOST_KEY)"
    compose
    exit 2
fi
echo "ok" > "$HDIR_LOCAL/reach.txt"

# --- the two remote scripts, generated as artifacts -------------------------
cat > "$DIR/remote_probe.sh" <<EOF
#!/usr/bin/env bash
# GENERATED by s10_bar1_driver.sh. Runs on the PVE host. Read-only.
set -uo pipefail
PHASE="\$1"
V=$NV_HOST/kernel-open
mkdir -p $HDIR
{
  echo "timestamp=\$(date -Is)"
  echo "kernel=\$(uname -r)"
  echo "regkey_line=\$(grep -i '^RegistryDwords:' /proc/driver/nvidia/params 2>/dev/null | head -1)"
  echo "srcversion_loaded=\$(cat /sys/module/nvidia/srcversion 2>/dev/null)"
  echo "srcversion_file=\$(modinfo -F srcversion \$V/nvidia.ko 2>/dev/null)"
  echo "strings_smallbar=\$(strings \$V/nvidia.ko 2>/dev/null | grep -c SMALLBAR_P2P)"
  echo "mod_nvidia=\$(lsmod | awk '\$1=="nvidia"{print \$3}')"
  echo "mod_nvidia_uvm=\$(lsmod | awk '\$1=="nvidia_uvm"{print \$3}')"
  echo "mod_nvidia_modeset=\$(lsmod | awk '\$1=="nvidia_modeset"{print \$3}')"
  echo "mod_dmabuf_holder=\$(lsmod | awk '\$1=="dmabuf_holder"{print \$3}')"
  echo "dmabuf_dev=\$(test -c /dev/dmabuf_holder && echo ja || echo nein)"
  echo "dmabuf_major=\$(stat -c '%Hr' /dev/dmabuf_holder 2>/dev/null)"
  echo "driver_version=\$(cat /proc/driver/nvidia/version 2>/dev/null | head -1)"
} > $HDIR/state_\$PHASE.txt
nvidia-smi --query-gpu=index,name,uuid,pci.bus_id,memory.total,memory.used \\
    --format=csv,noheader,nounits > $HDIR/cards_\$PHASE.csv 2>/dev/null
nvidia-smi --query-compute-apps=pid,process_name,used_memory \\
    --format=csv,noheader > $HDIR/compute_apps_\$PHASE.csv 2>/dev/null
lspci -Dn -d 10de: > $HDIR/pci.txt 2>/dev/null
# A snapshot FIRST, then grep the snapshot: grepping the live pipeline finds
# the grep's own command line and reports it as a module holder.
ps -eo pid,user,comm,args --no-headers > /tmp/bar1-ps.snap 2>/dev/null
grep -Ei 'nvtop|nvitop|gpustat|nvidia-smi|nvidia-persistenced|dcgm|nvidia_exporter|nvidia-gpu-exporter' \\
    /tmp/bar1-ps.snap > $HDIR/holders_\$PHASE.txt 2>/dev/null
true
EOF
chmod +x "$DIR/remote_probe.sh"

echo "== Zustand vor dem Eingriff =="
host_run_script 180 "$DIR/remote_probe.sh before" || echo "Probe (before) rc=$?"
sed -n 1,20p "$HDIR_LOCAL/state_before.txt" 2>/dev/null

# --- is the desired state already there? -----------------------------------
"$PY" "$BATTERY_DIR/s10_bar1_driver.py" --step-dir "$DIR" --gate-only
GATE=$?
case "$GATE" in
    0)
        echo "== Sollzustand liegt schon vor -- kein Eingriff =="
        echo "0" > "$HDIR_LOCAL/reload_performed.txt"
        cp "$HDIR_LOCAL/state_before.txt" "$HDIR_LOCAL/state_after.txt" 2>/dev/null
        cp "$HDIR_LOCAL/cards_before.csv" "$HDIR_LOCAL/cards_after.csv" 2>/dev/null
        cp "$HDIR_LOCAL/compute_apps_before.csv" "$HDIR_LOCAL/compute_apps_after.csv" 2>/dev/null
        cp "$HDIR_LOCAL/holders_before.txt" "$HDIR_LOCAL/holders_after.txt" 2>/dev/null
        nvidia-smi -L > "$HDIR_LOCAL/container_cards.txt" 2>&1
        compose
        exit $?
        ;;
    3) echo "== Sollzustand fehlt -- Neuladen noetig ==" ;;
    *)
        echo "Gate konnte nicht entscheiden (rc=$GATE)"
        compose
        exit 2
        ;;
esac

# --- who holds the modules? ------------------------------------------------
APPS="$(host_count_nonempty "$HDIR_LOCAL/compute_apps_before.csv")"
if [ "$APPS" -gt 0 ]; then
    echo "Rechenprozesse auf den Karten -- kein Eingriff:" \
        > "$HDIR_LOCAL/blocked.txt"
    cat "$HDIR_LOCAL/compute_apps_before.csv" >> "$HDIR_LOCAL/blocked.txt"
    echo "0" > "$HDIR_LOCAL/reload_performed.txt"
    compose
    exit 2
fi

HOLDERS="$(host_count_nonempty "$HDIR_LOCAL/holders_before.txt")"
if [ "$HOLDERS" -gt 0 ]; then
    if [ "$BAR1_VIEWER_KILL_OK" = "1" ]; then
        echo "== Bekannte Betrachter beenden (BAR1_VIEWER_KILL_OK=1) =="
        # Only the pids from the snapshot, one kill per pid, never a pattern.
        while read -r pid _rest; do
            [ -z "${pid//[^0-9]/}" ] && continue
            echo "kill $pid: $_rest" >> "$HDIR_LOCAL/viewers_killed.txt"
            host_ssh_for 60 "kill $pid 2>/dev/null; sleep 2; kill -9 $pid 2>/dev/null; true" \
                >/dev/null 2>&1
        done < "$HDIR_LOCAL/holders_before.txt"
        sleep 3
    else
        {
            echo "Prozesse halten die Module (BAR1_VIEWER_KILL_OK ist nicht 1):"
            cat "$HDIR_LOCAL/holders_before.txt"
        } > "$HDIR_LOCAL/blocked.txt"
        echo "0" > "$HDIR_LOCAL/reload_performed.txt"
        compose
        exit 2
    fi
fi

# --- host locks: nothing else may touch a card during the reload -----------
if ! host_locks_acquire "$BATTERY_STEP"; then
    echo "Host-Locks nicht zu bekommen" > "$HDIR_LOCAL/blocked.txt"
    echo "0" > "$HDIR_LOCAL/reload_performed.txt"
    compose
    exit 2
fi
trap 'host_locks_release' EXIT INT TERM

# --- the reload, recipe verbatim -------------------------------------------
cat > "$DIR/remote_reload.sh" <<EOF
#!/usr/bin/env bash
# GENERATED by s10_bar1_driver.sh. Runs on the PVE host. THIS ONE WRITES.
# Recipe: 04_BETRIEB.md "Treiber laden", with runtime-resolved PCI addresses.
set -uo pipefail
V=$NV_HOST/kernel-open

# nvidia_modeset MUST come out with it -- otherwise rmmod nvidia fails with
# "File exists".
for i in 1 2 3 4 5 6; do
  rmmod nvidia_uvm 2>/dev/null; rmmod nvidia_drm 2>/dev/null
  rmmod nvidia_modeset 2>/dev/null; rmmod nvidia 2>/dev/null
  lsmod | grep -q "^nvidia" || break
  sleep 3
done
if lsmod | grep -q "^nvidia"; then
  echo "FEHLER: nvidia laesst sich nicht entladen"
  lsmod | grep "^nvidia"
  exit 3
fi

# VGA (0300) and 3D controllers (0302) of vendor 10de, resolved now.
PCIS=\$(lspci -Dn -d 10de: | awk '\$2 ~ /^030[02]:/ {print \$1}')
echo "PCI-Resets: \$PCIS"
for c in \$PCIS; do
  echo 1 > /sys/bus/pci/devices/\$c/reset 2>/dev/null
done
sleep 4

insmod \$V/nvidia.ko NVreg_RegistryDwords=$BAR1_REGKEY || exit 4
insmod \$V/nvidia-uvm.ko || exit 5
lsmod | grep -q "^dmabuf_holder" || insmod $HOLDER_HOST || exit 6

# Creates /dev/nvidia* after a fresh insmod. Without it the first CUDA process
# is the one that discovers the nodes are missing.
nvidia-smi >/dev/null 2>&1
echo "geladen"
exit 0
EOF
chmod +x "$DIR/remote_reload.sh"

echo "== Treiber neu laden =="
host_run_script 420 "$DIR/remote_reload.sh" > "$HDIR_LOCAL/reload.log" 2>&1
RELOAD_RC=$?
echo "$RELOAD_RC" > "$HDIR_LOCAL/reload_rc.txt"
echo "1" > "$HDIR_LOCAL/reload_performed.txt"
tail -n 20 "$HDIR_LOCAL/reload.log"

echo "== Zustand danach =="
host_run_script 180 "$DIR/remote_probe.sh after" || echo "Probe (after) rc=$?"
nvidia-smi -L > "$HDIR_LOCAL/container_cards.txt" 2>&1

host_locks_release
trap - EXIT INT TERM

compose
exit $?
