#!/usr/bin/env bash
# Put the STOCK driver back. Standalone command, NOT a battery step.
#
#   bash s10_restore.sh [--force]
#
# The battery deliberately ends WITHOUT restoring: s11 and s12 run under the
# patch, and NCCL coexistence is measured, not assumed (four configurations,
# 37.11 / 64.65 / 359.35 us against 37.89 / 65.25 / 357.63 us -- all inside the
# spread). Leaving the patch loaded therefore costs nothing measurable, and
# unloading it between steps would only buy driver churn.
#
# This exists for the case where the operator wants the stock module back:
# a driver update, a foreign workload, a suspicion about the patch itself.
#
# It refuses to run while anything is on the cards, and it does not terminate
# viewers -- terminating a viewer is a user decision, and this script has no
# battery run behind it to record that decision in.

set -uo pipefail
cd "$(dirname "$0")"
source ./battery_common.sh
source ./battery_host.sh

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

OUT="${BATTERY_STEP_DIR:-/tmp/s10_restore.$$}"
mkdir -p "$OUT"

if ! host_reachable; then
    echo "STOP: Host $BAR1_HOST nicht erreichbar"
    exit 2
fi

echo "== Wer benutzt die Karten? =="
host_ssh_for 60 'nvidia-smi --query-compute-apps=pid,process_name,used_memory --format=csv,noheader' \
    > "$OUT/compute_apps.csv" 2>/dev/null
APPS="$(host_count_nonempty "$OUT/compute_apps.csv")"
if [ "$APPS" -gt 0 ] && [ "$FORCE" != 1 ]; then
    echo "STOP: $APPS Rechenprozess(e) auf den Karten:"
    cat "$OUT/compute_apps.csv"
    echo "Erst beenden lassen, dann erneut (oder --force, wenn der Operator das so will)."
    exit 2
fi

host_ssh_for 60 'ps -eo pid,user,comm,args --no-headers > /tmp/bar1-ps.snap; \
    grep -Ei "nvtop|nvitop|gpustat|nvidia-persistenced|dcgm" /tmp/bar1-ps.snap' \
    > "$OUT/holders.txt" 2>/dev/null
HOLDERS="$(host_count_nonempty "$OUT/holders.txt")"
if [ "$HOLDERS" -gt 0 ] && [ "$FORCE" != 1 ]; then
    echo "STOP: Prozesse halten die Module:"
    cat "$OUT/holders.txt"
    echo "Dieses Skript beendet keine Betrachter -- das ist eine Nutzer-Entscheidung."
    exit 2
fi

cat > "$OUT/remote_restore.sh" <<'EOF'
#!/usr/bin/env bash
# GENERATED by s10_restore.sh. Runs on the PVE host. Stock modules back.
set -uo pipefail
for i in 1 2 3 4 5 6; do
  rmmod nvidia_uvm 2>/dev/null; rmmod nvidia_drm 2>/dev/null
  rmmod nvidia_modeset 2>/dev/null; rmmod nvidia 2>/dev/null
  lsmod | grep -q "^nvidia" || break
  sleep 3
done
if lsmod | grep -q "^nvidia"; then
  echo "FEHLER: nvidia laesst sich nicht entladen"; lsmod | grep "^nvidia"; exit 3
fi
PCIS=$(lspci -Dn -d 10de: | awk '$2 ~ /^030[02]:/ {print $1}')
for c in $PCIS; do echo 1 > /sys/bus/pci/devices/$c/reset 2>/dev/null; done
sleep 4
modprobe nvidia || exit 4
modprobe nvidia_uvm || exit 5
nvidia-smi >/dev/null 2>&1
# Empty RegistryDwords is the proof that the stock module is back.
grep -i "^RegistryDwords:" /proc/driver/nvidia/params
cat /sys/module/nvidia/srcversion 2>/dev/null
echo "Serientreiber geladen"
EOF

echo "== Serientreiber laden =="
host_run_script 420 "$OUT/remote_restore.sh" 2>&1 | tee "$OUT/restore.log"
RC=${PIPESTATUS[0]}

echo "== Zustand =="
host_ssh_for 60 'grep -i "^RegistryDwords:" /proc/driver/nvidia/params; lsmod | grep -E "^nvidia|^dmabuf"' \
    2>&1 | tee "$OUT/state.txt"

echo "rc=$RC  Artefakte: $OUT"
exit "$RC"
