#!/usr/bin/env bash
# S11 -- one standard run over the BAR1 direct path, end to end.
#
# The question is NOT "does it boot". It is: do BOTH communicator groups really
# run over bar1, does the model answer coherently with a working spec path, and
# does the coverage bolt in htccl._select hold or hit.
#
# That bolt is the acceptance scenario of the parallel integration. Until
# all_gather exists in htccl_bar1, the standard run aborts with
#
#   RuntimeError: HTCCL: 'all_gather' mit <n> Byte waehrend einer
#   CUDA-Graph-Aufzeichnung, aber bar1 meldet handles(...) -> False.
#
# loudly and with a reason, which is correct behaviour and a FAIL of this step
# at the same time. The check gives it its own wording so nobody has to read a
# log to tell it apart from a boot that simply died.
#
# Gate first: benchmark/bar1_graph_check.py. SGLANG_HTCCL_GRAPH_FREIGABE=1
# without that evidence is a run whose numbers nobody can defend.
#
# The server log stays on the HOST. What comes into the run directory is the
# grep result and a bounded tail.

set -uo pipefail
cd "$(dirname "$0")"
source ./battery_common.sh
source ./battery_host.sh
source ./_bar1_host_boot.sh

DIR="${BATTERY_STEP_DIR:?BATTERY_STEP_DIR missing -- start through run_step.sh}"
PORT="${BAR1_PORT}"
HOST_WT="${BAR1_HOST_WT:-$WT}"
HOSTLOG="$BAR1_HOST_LOGDIR/s11.server.log"
HOSTPID="$BAR1_HOST_LOGDIR/s11.pid"
HOSTSMOKE="$BAR1_HOST_LOGDIR/s11.smoke.json"

compose() { "$PY" "$BATTERY_DIR/s11_bar1_e2e.py" --step-dir "$DIR" --port "$PORT" \
            --host-log "$HOSTLOG"; }

if ! host_reachable; then
    echo "STOP: host $BAR1_HOST not reachable"
    echo "unreachable" > "$DIR/host_unreachable.txt"
    compose
    exit 2
fi
if ! bar1_require_integration; then
    compose
    exit 2
fi

if ! host_locks_acquire "$BATTERY_STEP"; then
    echo "STOP: cannot acquire the host locks"
    echo "Host-Locks fremd gehalten -- nicht gebrochen" > "$DIR/blocked.txt"
    compose
    exit 2
fi
SERVER_PID=""
# The cleanup path. It reads TWO sources (the variable and the pidfile on the
# host) and checks afterwards that the process is really gone -- both, because
# on 2026-07-30 it silently did nothing: SERVER_PID held the boot message
# together with the pid, `kill -0` failed on that, and that counted as
# "nothing to kill". The server survived the run, held three cards and the
# dmabuf holder, and the next attempt ran against it.
cleanup() {
    bar1_kill_host_server "$SERVER_PID" "$HOSTPID" "$DIR/pyspy-host-server.txt" || true
    SERVER_PID=""
    host_locks_release
}
trap cleanup EXIT INT TERM

# --- nothing left over? -----------------------------------------------------
# BEFORE the gate, not just before the boot: the graph gate already builds
# BAR1 regions and gets ENOMEM from the holder while the cards are still
# occupied. That is exactly how all seven cases fell in 106 s in attempt 4 --
# a result that looked like a finding about bar1 and was one about cleanup.
if ! bar1_altlast_pruefen "$PORT" "$DIR/blocked.txt"; then
    compose
    exit 2
fi

# --- gate: can the direct path be captured in a CUDA graph? -----------------
cat > "$DIR/remote_graph_check.sh" <<EOF
#!/usr/bin/env bash
# GENERATED by s11_bar1_e2e.sh. Runs on the PVE host.
set -uo pipefail
V=$(host_path "$VENV")
W=$(host_path "$HOST_WT")
N=$(host_path "$BAR1_NV_SOURCE")
cd \$W
PYTHONPATH=\$W/python:\$V/lib/python3.12/site-packages \\
LD_LIBRARY_PATH=\$V/lib/python3.12/site-packages/nvidia/cu13/lib \\
CUDA_HOME=\$V/lib/python3.12/site-packages/nvidia/cu13 \\
SGLANG_HTCCL_BAR1_NV_QUELLE=\$N \\
TORCH_EXTENSIONS_DIR=$(host_path "$BAR1_EXTCACHE") \\
TORCH_CUDA_ARCH_LIST="8.6;12.0" MAX_JOBS=4 \\
  /spinning/miniforge3_local_install/bin/python3.12 benchmark/bar1_graph_check.py 0,1,2
EOF
chmod +x "$DIR/remote_graph_check.sh"

echo "== Gate: bar1_graph_check =="
host_run_script 1200 "$DIR/remote_graph_check.sh" > "$DIR/graph_check.txt" 2>&1
echo "$?" > "$DIR/graph_check_rc.txt"
tail -n 12 "$DIR/graph_check.txt"

# --- the standard run ------------------------------------------------------
echo "== Standard run, arm bar1 =="
bar1_write_boot_script "$DIR/remote_boot_bar1.sh" bar1 "$HOSTLOG" "$HOSTPID" "$PORT" || {
    compose; exit 2; }
SERVER_PID="$(bar1_boot_start "$DIR/remote_boot_bar1.sh" "$HOSTPID")" || SERVER_PID=""
# Not merely "not empty": a number. A pid that is none otherwise only shows up
# in the cleanup path, and there it looks like a dead process.
if ! bar1_pid_ok "$SERVER_PID"; then
    echo "server start returned no usable pid ('$SERVER_PID')"
    SERVER_PID=""
    # The server CAN be running all the same -- the pidfile on the host is the
    # second source, and that is exactly what cleanup takes it for.
    host_tail_into "$HOSTLOG" "$DIR/server.log" 400
    compose
    exit 1
fi
echo "Host-pid $SERVER_PID"
echo "$SERVER_PID" > "$DIR/host_pids"

if ! host_wait_for_server "$PORT" 900; then
    bar1_kill_host_server "$SERVER_PID" "$HOSTPID" "$DIR/pyspy-host-server.txt" || true
    SERVER_PID=""
    host_tail_into "$HOSTLOG" "$DIR/server.log" 400
    compose
    exit 1
fi

# --- smoke: coherence and a live spec path ---------------------------------
# TWO reasons why this is /generate and not /v1/chat/completions.
#
# 1. THE CHAT TEMPLATE. The run of 2026-07-30 answered the very same request
#    at temperature 0 with a thinking preamble ("Here's a thinking process:
#    1. Analyze User Input ...") instead of counting. The 128 tokens went on
#    that (finish_reason=length), the numbers never got their turn -- and the
#    coherence counter reported 3, because it took the bullet points OF THE
#    PREAMBLE for the answer. /generate puts the text through without a
#    template; a preamble cannot arise there at all, rather than switching it
#    off with a flag whose support depends on the model's template.
# 2. meta_info. On the chat path it is opt-in (protocol.py:723
#    return_meta_info=False, serving_chat.py:1376 returns None otherwise); on
#    /generate it always comes along -- and only there sits
#    spec_accept_length, which this step needs.
#
# A continuation prompt instead of an instruction: continuing "1 2 3 4" is not
# a task anyone can think about. 512 tokens is enough air that the limit never
# truncates the answer.
#
# What the criterion reads out of it is NOT "did it dutifully count to 20".
# Attempt 4 continued " 5 6 7 8 9 10" correctly and then drifted into a
# Russian forum post -- the characteristic of a raw continuation with no
# instruction, not damage. What is checked is therefore (a) an anchor of four
# immediately and gaplessly correct numbers and (b) that the text is
# well-formed (printable, no token loop). The reasoning, together with the
# thresholds measured against the artifact, sits in s11_bar1_e2e.py.
echo "== Smoke request (/generate, continuation) =="
host_ssh_for 180 "curl -s -m 120 http://127.0.0.1:$PORT/generate \
  -H 'Content-Type: application/json' -d '{\"text\": \"1 2 3 4\", \
  \"sampling_params\": {\"temperature\": 0, \"max_new_tokens\": 512}}' \
  > $HOSTSMOKE; wc -c < $HOSTSMOKE" \
  > "$DIR/smoke_bytes.txt" 2>&1
host_ssh_for 60 "cat $HOSTSMOKE" > "$DIR/smoke.json" 2>/dev/null

host_ssh_for 60 "curl -sf -m 20 http://127.0.0.1:$PORT/get_server_info" \
    > "$DIR/server_info.json" 2>/dev/null

# --- harvest the log evidence, then shut down ------------------------------
echo "== Evidence out of the server log (stays on the host) =="
host_grep_into "$HOSTLOG" "$DIR/htccl_lines.txt" \
    "HTCCL-BAR1: Aufbau in" \
    "BAR1-Kasse dieser Karte nach Gruppe" \
    "HTCCL enabled for group" \
    "ERREICHT=" \
    "waehrend einer CUDA-Graph-Aufzeichnung" \
    "CUDA out of memory" \
    "torch.OutOfMemoryError" \
    "NCCL error" \
    "Traceback (most recent call last)"
host_tail_into "$HOSTLOG" "$DIR/server.log" 400
wc -l "$DIR/htccl_lines.txt" "$DIR/server.log" 2>/dev/null

cleanup
trap - EXIT INT TERM

compose
exit $?
