#!/usr/bin/env bash
# S11 -- one standard run over the BAR1 direct path, end to end.
#
# The question is NOT "does it boot". It is: do BOTH communicator groups really
# run over bar1, does the model answer coherently with a working spec path, and
# does the coverage bolt in htccl._select hold or hit.
#
# That bolt is the acceptance scenario of the parallel integration. Until
# all_gather exists in htccl_bar1, the standard run aborts with
#
#   RuntimeError: HTCCL: 'all_gather' mit <n> Byte waehrend einer
#   CUDA-Graph-Aufzeichnung, aber bar1 meldet handles(...) -> False.
#
# loudly and with a reason, which is correct behaviour and a FAIL of this step
# at the same time. The check gives it its own wording so nobody has to read a
# log to tell it apart from a boot that simply died.
#
# Gate first: benchmark/bar1_graph_check.py. SGLANG_HTCCL_GRAPH_FREIGABE=1
# without that evidence is a run whose numbers nobody can defend.
#
# The server log stays on the HOST. What comes into the run directory is the
# grep result and a bounded tail.

set -uo pipefail
cd "$(dirname "$0")"
source ./battery_common.sh
source ./battery_host.sh
source ./_bar1_host_boot.sh

DIR="${BATTERY_STEP_DIR:?BATTERY_STEP_DIR fehlt -- ueber run_step.sh starten}"
PORT="${BAR1_PORT}"
HOST_WT="${BAR1_HOST_WT:-$WT}"
HOSTLOG="$BAR1_HOST_LOGDIR/s11.server.log"
HOSTPID="$BAR1_HOST_LOGDIR/s11.pid"
HOSTSMOKE="$BAR1_HOST_LOGDIR/s11.smoke.json"

compose() { "$PY" "$BATTERY_DIR/s11_bar1_e2e.py" --step-dir "$DIR" --port "$PORT" \
            --host-log "$HOSTLOG"; }

if ! host_reachable; then
    echo "STOP: Host $BAR1_HOST nicht erreichbar"
    echo "unreachable" > "$DIR/host_unreachable.txt"
    compose
    exit 2
fi
if ! bar1_require_integration; then
    compose
    exit 2
fi

if ! host_locks_acquire "$BATTERY_STEP"; then
    echo "STOP: Host-Locks nicht zu bekommen"
    echo "Host-Locks fremd gehalten -- nicht gebrochen" > "$DIR/blocked.txt"
    compose
    exit 2
fi
SERVER_PID=""
# Der Aufraeumpfad. Er liest ZWEI Quellen (Variable und Pidfile auf dem Host)
# und prueft nach, ob der Prozess wirklich weg ist -- beides, weil er am
# 2026-07-30 stillschweigend nichts getan hat: SERVER_PID enthielt die
# Bootmeldung samt pid, `kill -0` scheiterte daran, und das galt als "nichts
# zu toeten". Der Server ueberlebte den Lauf, hielt drei Karten und den
# dmabuf-Halter, und der naechste Anlauf lief gegen ihn.
cleanup() {
    bar1_kill_host_server "$SERVER_PID" "$HOSTPID" "$DIR/pyspy-host-server.txt" || true
    SERVER_PID=""
    host_locks_release
}
trap cleanup EXIT INT TERM

# --- keine Altlast? --------------------------------------------------------
# VOR dem Tor, nicht erst vor dem Boot: schon das Graph-Tor baut BAR1-Regionen
# auf und bekommt vom Halter ENOMEM, wenn die Karten noch belegt sind. Genau
# so sind in Anlauf 4 alle sieben Faelle in 106 s durchgefallen -- ein
# Ergebnis, das wie ein Befund ueber bar1 aussah und einer ueber das
# Aufraeumen war.
if ! bar1_altlast_pruefen "$PORT" "$DIR/blocked.txt"; then
    compose
    exit 2
fi

# --- gate: can the direct path be captured in a CUDA graph? -----------------
cat > "$DIR/remote_graph_check.sh" <<EOF
#!/usr/bin/env bash
# GENERATED by s11_bar1_e2e.sh. Runs on the PVE host.
set -uo pipefail
V=$(host_path "$VENV")
W=$(host_path "$HOST_WT")
N=$(host_path "$BAR1_NV_SOURCE")
cd \$W
PYTHONPATH=\$W/python:\$V/lib/python3.12/site-packages \\
LD_LIBRARY_PATH=\$V/lib/python3.12/site-packages/nvidia/cu13/lib \\
CUDA_HOME=\$V/lib/python3.12/site-packages/nvidia/cu13 \\
SGLANG_HTCCL_BAR1_NV_QUELLE=\$N \\
TORCH_EXTENSIONS_DIR=$(host_path "$BAR1_EXTCACHE") \\
TORCH_CUDA_ARCH_LIST="8.6;12.0" MAX_JOBS=4 \\
  /spinning/miniforge3_local_install/bin/python3.12 benchmark/bar1_graph_check.py 0,1,2
EOF
chmod +x "$DIR/remote_graph_check.sh"

echo "== Tor: bar1_graph_check =="
host_run_script 1200 "$DIR/remote_graph_check.sh" > "$DIR/graph_check.txt" 2>&1
echo "$?" > "$DIR/graph_check_rc.txt"
tail -n 12 "$DIR/graph_check.txt"

# --- the standard run ------------------------------------------------------
echo "== Standardlauf, Arm bar1 =="
bar1_write_boot_script "$DIR/remote_boot_bar1.sh" bar1 "$HOSTLOG" "$HOSTPID" "$PORT" || {
    compose; exit 2; }
SERVER_PID="$(bar1_boot_start "$DIR/remote_boot_bar1.sh" "$HOSTPID")" || SERVER_PID=""
# Nicht nur "nicht leer": eine Zahl. Ein pid, der keiner ist, faellt sonst
# erst im Aufraeumpfad auf, und dort sieht er aus wie ein toter Prozess.
if ! bar1_pid_ok "$SERVER_PID"; then
    echo "Server-Start lieferte keinen brauchbaren pid ('$SERVER_PID')"
    SERVER_PID=""
    # Der Server KANN trotzdem laufen -- die Pidfile auf dem Host ist die
    # zweite Quelle, und genau dafuer nimmt cleanup sie.
    host_tail_into "$HOSTLOG" "$DIR/server.log" 400
    compose
    exit 1
fi
echo "Host-pid $SERVER_PID"
echo "$SERVER_PID" > "$DIR/host_pids"

if ! host_wait_for_server "$PORT" 900; then
    bar1_kill_host_server "$SERVER_PID" "$HOSTPID" "$DIR/pyspy-host-server.txt" || true
    SERVER_PID=""
    host_tail_into "$HOSTLOG" "$DIR/server.log" 400
    compose
    exit 1
fi

# --- smoke: coherence and a live spec path ---------------------------------
# ZWEI Gruende, warum das /generate ist und nicht /v1/chat/completions.
#
# 1. DAS CHAT-TEMPLATE. Der Lauf vom 2026-07-30 hat denselben Request bei
#    Temperatur 0 mit einer Denk-Praeambel beantwortet ("Here's a thinking
#    process: 1. Analyze User Input ...") statt zu zaehlen. Die 128 Token
#    waren davon verbraucht (finish_reason=length), die Zahlen kamen nie
#    dran -- und der Kohaerenzzaehler meldete 3, weil er die
#    Aufzaehlungspunkte DER PRAEAMBEL fuer die Antwort hielt. /generate
#    schickt den Text ohne Template durch; eine Praeambel kann dort nicht
#    entstehen, statt sie mit einem Schalter abzustellen, dessen
#    Unterstuetzung am Template des Modells haengt.
# 2. meta_info. Auf dem Chat-Pfad ist es opt-in (protocol.py:723
#    return_meta_info=False, serving_chat.py:1376 gibt sonst None), auf
#    /generate kommt es immer mit -- und nur dort steht
#    spec_accept_length, das dieser Schritt braucht.
#
# Fortsetzungs-Prompt statt Anweisung: "1 2 3 4" fortzusetzen ist keine
# Aufgabe, ueber die sich nachdenken laesst. 512 Token sind Luft genug, dass
# die Grenze nie die Antwort abschneidet.
#
# Was das Kriterium daraus liest, ist NICHT "hat er brav bis 20 gezaehlt".
# Anlauf 4 zaehlte " 5 6 7 8 9 10" korrekt weiter und driftete dann in einen
# russischen Forumtext -- die Charakteristik einer rohen Fortsetzung ohne
# Anweisung, kein Schaden. Geprueft wird deshalb (a) ein Anker aus vier
# unmittelbar und lueckenlos richtigen Zahlen und (b) dass der Text
# wohlgeformt ist (druckbar, keine Tokenschleife). Die Begruendung samt der
# am Artefakt gemessenen Schwellen steht in s11_bar1_e2e.py.
echo "== Smoke-Request (/generate, Fortsetzung) =="
host_ssh_for 180 "curl -s -m 120 http://127.0.0.1:$PORT/generate \
  -H 'Content-Type: application/json' -d '{\"text\": \"1 2 3 4\", \
  \"sampling_params\": {\"temperature\": 0, \"max_new_tokens\": 512}}' \
  > $HOSTSMOKE; wc -c < $HOSTSMOKE" \
  > "$DIR/smoke_bytes.txt" 2>&1
host_ssh_for 60 "cat $HOSTSMOKE" > "$DIR/smoke.json" 2>/dev/null

host_ssh_for 60 "curl -sf -m 20 http://127.0.0.1:$PORT/get_server_info" \
    > "$DIR/server_info.json" 2>/dev/null

# --- harvest the log evidence, then shut down ------------------------------
echo "== Belege aus dem Serverlog (bleibt auf dem Host) =="
host_grep_into "$HOSTLOG" "$DIR/htccl_lines.txt" \
    "HTCCL-BAR1: Aufbau in" \
    "BAR1-Kasse dieser Karte nach Gruppe" \
    "HTCCL enabled for group" \
    "ERREICHT=" \
    "waehrend einer CUDA-Graph-Aufzeichnung" \
    "CUDA out of memory" \
    "torch.OutOfMemoryError" \
    "NCCL error" \
    "Traceback (most recent call last)"
host_tail_into "$HOSTLOG" "$DIR/server.log" 400
wc -l "$DIR/htccl_lines.txt" "$DIR/server.log" 2>/dev/null

cleanup
trap - EXIT INT TERM

compose
exit $?
