#!/usr/bin/env bash
# S12 -- the measurement everything runs towards: does the multi-session
# prefill curve stay flat over the direct path, or does it start to rise?
#
# Over the host path the curve is flat (1190/1097/1144/1105/1122 tok/s over
# 1/2/4/8/16 sessions) at 65-90 % collective time -- more sessions buy nothing
# because the collectives, not the arithmetic units, are already saturated. If
# the ceiling is the detour, it falls with the detour. That is the finding this
# step collects. IT DOES NOT GRADE IT: flat and rising are both results, and
# the check has no opinion about which one happened.
#
# INTERLEAVED, not blockwise (measurement rule 5): per session count the bar1
# arm and the baseline arm run back to back, then the next session count.
# Eight boots for four points per arm, and that is the price of not comparing
# two different afternoons. Blockwise would be one boot per arm and worthless.
#
# The two arms differ in EXACTLY the three SGLANG_HTCCL* variables. The boot
# script is generated from one template for both, so they cannot drift.
#
# Each boot also leaves its ERREICHT lines behind: a bar1 arm whose second
# communicator group quietly fell back to gloo would look like a bar1 point and
# be a mixed one. That check is in the check script, the evidence is collected
# here.

set -uo pipefail
cd "$(dirname "$0")"
source ./battery_common.sh
source ./battery_host.sh
source ./_bar1_host_boot.sh

DIR="${BATTERY_STEP_DIR:?BATTERY_STEP_DIR missing -- start through run_step.sh}"
PORT="${BAR1_PORT}"
SESSIONS="${S12_SESSIONS:-1 4 8 16}"
POINT_S="${S12_POINT_SECONDS:-15}"
WARMUP_S="${S12_WARMUP_SECONDS:-8}"
PROMPT_TOKENS="${S12_PROMPT_TOKENS:-2048}"

mkdir -p "$DIR/belege" "$DIR/logs"
DIR_HOST="$(host_path "$DIR")" || exit 2
DRIVER_HOST="$(host_path "$BATTERY_DIR/s12_prefill_kurve.py")" || exit 2

summarize() {
    "$PY" "$BATTERY_DIR/s12_prefill_kurve.py" --mode zusammenfassen --step-dir "$DIR"
}

if ! host_reachable; then
    echo "STOP: host $BAR1_HOST not reachable"
    echo "unreachable" > "$DIR/host_unreachable.txt"
    summarize
    exit 2
fi
if ! bar1_require_integration; then
    summarize
    exit 2
fi
if ! host_locks_acquire "$BATTERY_STEP"; then
    echo "STOP: host locks not obtainable"
    echo "Host-Locks fremd gehalten -- nicht gebrochen" > "$DIR/blocked.txt"
    summarize
    exit 2
fi

SERVER_PID=""
# EIGHT boots in this step, so eight chances to leave a server standing. The
# same cleanup path as in s11, and for the same reason: `bar1_boot_start` used
# to put the boot message on stdout too, `kill -0` choked on it, and that
# counted as "nothing to kill".
cleanup() {
    bar1_kill_host_server "$SERVER_PID" "${HOSTPID:-}" \
        "$DIR/pyspy-host-cleanup.txt" || true
    SERVER_PID=""
    host_locks_release
}
trap cleanup EXIT INT TERM

# No run against the leftovers of an earlier attempt. Here they would cost even
# more than in s11: eight boots would measure the wrong server eight times.
if ! bar1_altlast_pruefen "$PORT" "$DIR/blocked.txt"; then
    summarize
    exit 2
fi

# The measurement driver runs ON THE HOST (stdlib only, host python) because
# the server listens on the host's loopback. It writes straight into the run
# directory through the path mapping, which is what makes the live table live.
cat > "$DIR/remote_messen.sh" <<EOF
#!/usr/bin/env bash
# GENERATED by s12_prefill_kurve.sh. Runs on the PVE host.
set -uo pipefail
/spinning/miniforge3_local_install/bin/python3.12 $DRIVER_HOST \\
  --mode messen --port $PORT --out-dir $DIR_HOST \\
  --point-seconds $POINT_S --warmup-seconds $WARMUP_S \\
  --prompt-tokens $PROMPT_TOKENS \\
  --arm "\$1" --sessions "\$2" --folge "\$3" --server-log "\$4"
EOF
chmod +x "$DIR/remote_messen.sh"

SEQ=0
ABORT=""

for N in $SESSIONS; do
    for ARM in bar1 grundlinie; do
        SEQ=$((SEQ + 1))
        HOSTLOG="$BAR1_HOST_LOGDIR/s12.$ARM.$N.log"
        HOSTPID="$BAR1_HOST_LOGDIR/s12.$ARM.$N.pid"
        echo "== [$SEQ] arm $ARM, $N session(s) =="

        bar1_write_boot_script "$DIR/remote_boot_${ARM}_${N}.sh" "$ARM" \
            "$HOSTLOG" "$HOSTPID" "$PORT" || { ABORT="boot script $ARM/$N"; break; }
        SERVER_PID="$(bar1_boot_start "$DIR/remote_boot_${ARM}_${N}.sh" "$HOSTPID")" \
            || SERVER_PID=""
        if ! bar1_pid_ok "$SERVER_PID"; then
            SERVER_PID=""
            host_tail_into "$HOSTLOG" "$DIR/logs/${ARM}_${N}.tail.txt" 200
            ABORT="server start $ARM/$N without pid"
            break
        fi
        echo "$SERVER_PID" >> "$DIR/host_pids"

        if ! host_wait_for_server "$PORT" 900; then
            host_tail_into "$HOSTLOG" "$DIR/logs/${ARM}_${N}.tail.txt" 200
            cleanup_pid="$SERVER_PID"
            bar1_kill_host_server "$cleanup_pid" "$HOSTPID" \
                "$DIR/pyspy-host-$cleanup_pid.txt" || true
            SERVER_PID=""
            ABORT="server $ARM/$N never came up"
            break
        fi

        # The arm's own evidence, BEFORE the numbers: which transport each
        # communicator group really got.
        host_grep_into "$HOSTLOG" "$DIR/belege/${SEQ}_${ARM}_${N}.txt" \
            "HTCCL enabled for group" \
            "ACHIEVED=" \
            "HTCCL-BAR1: setup in" \
            "during a CUDA graph capture"

        # The server log goes along: accept len and the tick rate of the decode
        # only exist in the scheduler's own lines. Read live, while the server
        # still runs -- after the kill the file is still there, but the run
        # directory is not where it lives.
        host_run_script 900 "$DIR/remote_messen.sh" "$ARM" "$N" "$SEQ" \
            "$HOSTLOG" >> "$DIR/messen.log" 2>&1
        MRC=$?
        echo "  measurement rc=$MRC"

        host_grep_into "$HOSTLOG" "$DIR/logs/${ARM}_${N}.fatal.txt" \
            "CUDA out of memory" "torch.OutOfMemoryError" "NCCL error" \
            "Traceback (most recent call last)"
        host_tail_into "$HOSTLOG" "$DIR/logs/${ARM}_${N}.tail.txt" 200

        # Cleaned up and then verified, not merely kicked off: a server that
        # survives into the next boot turns eight measured points into eight
        # measurements of the same process.
        bar1_kill_host_server "$SERVER_PID" "$HOSTPID" \
            "$DIR/pyspy-host-$SERVER_PID.txt" || true
        SERVER_PID=""
        # The next boot must not race the dying one for VRAM.
        sleep 20

        if [ "$MRC" != 0 ]; then
            ABORT="measurement $ARM/$N rc=$MRC"
            break
        fi
    done

    # 6b applies to this sonnet step as well: after every pair the table is
    # rewritten from the persisted points, so the run can be watched live.
    echo "== interim state after $N session(s) =="
    summarize

    [ -n "$ABORT" ] && break
done

cleanup
trap - EXIT INT TERM

summarize
if [ -n "$ABORT" ]; then
    echo "aborted: $ABORT" | tee "$DIR/abbruch.txt"
    exit 1
fi
exit 0
