#!/usr/bin/env bash
# S14 -- task #294: does the decode bonus of the #293 prefill window hold up?
#
# The claim under test comes out of s13 as a by-product: ms/Verify 6,07 for
# bar1_hi against 9,09 for the NCCL anchor at bs=16, a factor of 1,50. Three
# ticks per point produced it, the batch size was not constant inside them, and
# the two arms did not share a reserve. This step measures the same quantity
# with a decode-oriented setup and its own noise floor; s14_decode_punkt.py
# carries the reasoning for every part of that setup.
#
# WHAT DIFFERS FROM S13, and why each difference is necessary:
#
#   * --decode-log-interval 10 instead of the default 40. The tick is the
#     sample, and at 40 a 15 s window at bs=16 yields three of them. Identical
#     on both arms, so it cannot move the ratio.
#   * The NCCL anchor carries the SAME reserve as bar1_hi. In s13 the 9,09 came
#     from `nccl` at 3000,2700,2700 while the 6,07 came from `bar1_hi` at
#     4500,4200,4200 -- a different KV pool on the two sides of the ratio.
#   * Four batch sizes per boot, and bs=16 twice: once first, once last. The
#     two bs=16 points of one boot are a within-boot A-vs-A that every boot
#     brings along for free, and a boot whose two ends disagree is a boot whose
#     middle cannot be trusted either.
#
# ROUNDS, NOT BLOCKS, as in s13: each round walks the arm list in the same
# order, so a warming card or a drifting clock hits both arms alike, and two
# rounds of the same arm are the between-boot spread.

set -uo pipefail
cd "$(dirname "$0")"
source ./battery_common.sh
source ./battery_host.sh
source ./_bar1_host_boot.sh

DIR="${BATTERY_STEP_DIR:?BATTERY_STEP_DIR missing}"
PORT="${BAR1_PORT}"
CONTEXT_TOKENS="${S14_CONTEXT_TOKENS:-2048}"
# What --context-length in the boot recipe pins. The driver reads the server's
# own value on top of this; the pin is the fallback, not the authority.
MODEL_CONTEXT="${S14_MODEL_CONTEXT:-32768}"
RAMP_S="${S14_RAMP_SECONDS:-6}"
WINDOW_S="${S14_WINDOW_SECONDS:-15}"
DRAIN_S="${S14_DRAIN_SECONDS:-5}"
ROUNDS="${S14_RUNDEN:-1}"
ROUND_START="${S14_RUNDE_START:-1}"
# Batch sizes in the order they run inside one boot.
BS_LIST="${S14_BS:-16 1 4 8 16}"

# The reserve both arms share. Pinned in one place so the anchor can never
# drift away from the arm it anchors.
RESERVE="--rank-auto-reserve-mib 4500,4200,4200"
# The measurement instrument, identical on both arms.
LOGARG="--decode-log-interval ${S14_LOG_INTERVAL:-10}"

# name | transport arm | extra env | extra server args
ARM_TABLE=(
    "nccl_hi|grundlinie||$RESERVE $LOGARG"
    "bar1_hi|bar1||$RESERVE $LOGARG"
)
S14_NUR="${S14_NUR:-}"

mkdir -p "$DIR/belege" "$DIR/logs"
DIR_HOST="$(host_path "$DIR")" || exit 2
DRIVER_HOST="$(host_path "$BATTERY_DIR/s14_decode_punkt.py")" || exit 2

if ! host_reachable; then
    echo "STOP: host $BAR1_HOST not reachable"; exit 2
fi
if ! bar1_require_integration; then exit 2; fi
if ! host_locks_acquire "${BATTERY_STEP:-s14}"; then
    echo "STOP: host locks not obtainable"
    echo "Host-Locks fremd gehalten -- nicht gebrochen" > "$DIR/blocked.txt"
    exit 2
fi

SERVER_PID=""
HOSTPID=""

s14_warte_auf_server() {  # $1 = port, $2 = host pid, $3 = budget_s
    local port="$1" pid="$2" budget="${3:-600}" t0
    t0=$(date +%s)
    while [ $(( $(date +%s) - t0 )) -lt "$budget" ]; do
        if host_ssh_for 40 "curl -sf -m 5 http://127.0.0.1:$port/health >/dev/null" \
            >/dev/null 2>&1; then
            echo "host server up after $(( $(date +%s) - t0 ))s"
            return 0
        fi
        if ! host_ssh_for 40 "kill -0 $pid 2>/dev/null" >/dev/null 2>&1; then
            echo "host server $pid died before it ever answered " \
                 "(after $(( $(date +%s) - t0 ))s)" >&2
            return 2
        fi
        sleep 10
    done
    echo "host server not up within ${budget}s" >&2
    return 1
}

cleanup() {
    bar1_kill_host_server "$SERVER_PID" "${HOSTPID:-}" \
        "$DIR/pyspy-host-cleanup.txt" || true
    SERVER_PID=""
    host_locks_release
}
trap cleanup EXIT INT TERM

cat > "$DIR/remote_decode.sh" <<EOF
#!/usr/bin/env bash
# GENERATED by s14_decode_verif.sh. Runs on the PVE host.
set -uo pipefail
/spinning/miniforge3_local_install/bin/python3.12 $DRIVER_HOST \\
  --port $PORT --out-dir $DIR_HOST \\
  --context-tokens $CONTEXT_TOKENS --model-context-tokens $MODEL_CONTEXT \\
  --ramp-seconds $RAMP_S --window-seconds $WINDOW_S --drain-seconds $DRAIN_S \\
  --arm "\$1" --bs "\$2" --folge "\$3" --server-log "\$4"
EOF
chmod +x "$DIR/remote_decode.sh"

SEQ=0
ABORT=""

for ROUND in $(seq "$ROUND_START" $((ROUND_START + ROUNDS - 1))); do
    for ROW in "${ARM_TABLE[@]}"; do
        NAME="${ROW%%|*}"
        REST="${ROW#*|}"
        TARM="${REST%%|*}"
        REST="${REST#*|}"
        EENV="${REST%%|*}"
        EARGS="${REST#*|}"

        if [ -n "$S14_NUR" ]; then
            case " $S14_NUR " in *" $NAME "*) ;; *) continue ;; esac
        fi

        ARM="${NAME}_r${ROUND}"
        HOSTLOG="$BAR1_HOST_LOGDIR/s14.$ARM.log"
        HOSTPID="$BAR1_HOST_LOGDIR/s14.$ARM.pid"
        echo "== round $ROUND, arm $NAME (transport $TARM) =="

        if ! bar1_altlast_pruefen "$PORT" "$DIR/blocked.txt"; then
            ABORT="leftover server before $ARM"; break
        fi

        BAR1_EXTRA_ENV="$EENV" BAR1_EXTRA_ARGS="$EARGS" \
            bar1_write_boot_script "$DIR/remote_boot_${ARM}.sh" "$TARM" \
                "$HOSTLOG" "$HOSTPID" "$PORT" \
            || { ABORT="boot script $ARM"; break; }

        SERVER_PID="$(bar1_boot_start "$DIR/remote_boot_${ARM}.sh" "$HOSTPID")" \
            || SERVER_PID=""
        if ! bar1_pid_ok "$SERVER_PID"; then
            SERVER_PID=""
            host_tail_into "$HOSTLOG" "$DIR/logs/${ARM}.tail.txt" 200
            echo "no pid" > "$DIR/logs/${ARM}.bootfehler.txt"
            echo "  ARM SKIPPED: server start without a pid"
            continue
        fi
        echo "$SERVER_PID" >> "$DIR/host_pids"

        if ! s14_warte_auf_server "$PORT" "$SERVER_PID" 600; then
            host_grep_into "$HOSTLOG" "$DIR/logs/${ARM}.bootfehler.txt" \
                "Bar1Unavailable" "ColdBuildWindowError" "CUDA out of memory" \
                "torch.OutOfMemoryError" "NCCL error" "Capture cuda graph failed" \
                "Received sigquit"
            host_tail_into "$HOSTLOG" "$DIR/logs/${ARM}.tail.txt" 200
            bar1_kill_host_server "$SERVER_PID" "$HOSTPID" \
                "$DIR/pyspy-host-$SERVER_PID.txt" || true
            SERVER_PID=""
            echo "  ARM SKIPPED: server never came up (reason in logs/${ARM}.bootfehler.txt)"
            sleep 20
            continue
        fi

        # ACHIEVED= per group BEFORE any number, same rule as s13: an arm whose
        # second communicator group quietly fell back is a mixed point, and a
        # decode graph that silently did not get captured would otherwise be
        # reported as a graph measurement.
        host_grep_into "$HOSTLOG" "$DIR/belege/${ARM}.txt" \
            "barlink enabled for group" \
            "ACHIEVED=" \
            "barlink-BAR1: setup in" \
            "CUDA graph begin" \
            "CUDA graph end" \
            "Disable cuda graph" \
            "during a CUDA graph capture"

        MRC=0
        for BS in $BS_LIST; do
            SEQ=$((SEQ + 1))
            echo "   point bs=$BS"
            host_run_script 600 "$DIR/remote_decode.sh" "$ARM" "$BS" "$SEQ" \
                "$HOSTLOG" >> "$DIR/messen.log" 2>&1
            RC=$?
            [ "$RC" != 0 ] && MRC=$RC
        done
        echo "  measurement rc=$MRC"

        host_grep_into "$HOSTLOG" "$DIR/logs/${ARM}.fatal.txt" \
            "CUDA out of memory" "torch.OutOfMemoryError" "NCCL error" \
            "Traceback (most recent call last)"
        host_tail_into "$HOSTLOG" "$DIR/logs/${ARM}.tail.txt" 120

        bar1_kill_host_server "$SERVER_PID" "$HOSTPID" \
            "$DIR/pyspy-host-$SERVER_PID.txt" || true
        SERVER_PID=""
        sleep 20

        if [ "$MRC" != 0 ]; then
            printf 'measurement rc=%s\n' "$MRC" > "$DIR/logs/${ARM}.messfehler.txt"
            echo "  POINT MISSING: measurement rc=$MRC (reason in logs/${ARM}.fatal.txt)"
        fi
    done
    [ -n "$ABORT" ] && break
    echo "== round $ROUND done =="
done

cleanup
trap - EXIT INT TERM

if [ -n "$ABORT" ]; then
    echo "aborted: $ABORT" | tee "$DIR/abbruch.txt"
    exit 1
fi
exit 0
