"""HW-AP0 1525: hw_sim as the progress meter of the hardware-generic work.

What this file pins (all CPU, no GPU, no NVML):

1. the CATALOG / SEED_CARDS know the cards of the release example configurations
   (RTX 3070 8 GiB, RTX 5070 12 GiB, RTX 5070 Ti 16 GiB) and say which figures no
   card ever backed ("HW-BORROWED/unbelegt"); the sm89 cards say "am Metall nie
   gemessen";
2. the model profiles of ``fit_profiles_data/`` are DERIVED from the
   ``config.json`` fixtures by ``hw_fit.derive_profile`` (not typed in) and
   agree with figures the launcher printed (PLE 97719 MiB stays on disk; dense
   3377 MiB; KV 1088 B/token/layer fp8);
3. the fit bound (``hw_fit.evaluate``) reproduces the by-hand verdicts of
   1520 A: the D host of the NF release needs 17,3 GiB without / 19,3 GiB with
   the mamba slots, 3x3070 / 3x3080-10G / 3x5070Ti do not fit, 2x3090 does; a
   27B INT8 fits 5090 + 3080 but not 3080 + 3080; and the module knows no model
   name (a profile is data);
4. the P-CHUNK-MODEL false alarm is gone: the check runs only under
   ``--p-chunk-policy dynamic``;
5. the progress meter (``hw_progress``) prints one row per example configuration x
   model and equals a golden generated by the meter itself (review object).

REGENERATE the progress golden after a change that moves a cell ON PURPOSE::

    CUDA_VISIBLE_DEVICES= PYTHONPATH=python python3 -m flliper.srt.pdflip.hw_progress \\
        --write-golden test/registered/unit/pdflip/fixtures/hw_progress_1525/progress_golden.json
"""

import ast
import contextlib
import dataclasses
import io
import json
import os
import re
import unittest
from unittest import mock

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")

import msgspec

from flliper.srt.planner import card_library as CL
from flliper.srt.pdflip import hw_fit as HF
from flliper.srt.pdflip import hw_progress as HP
from flliper.srt.pdflip import hw_sim as HS
from flliper.srt.pdflip import refusals
from flliper.test.ci.ci_register import register_cpu_ci

register_cpu_ci(est_time=40, suite="stage-a-pdflip-unit")

HERE = os.path.dirname(os.path.abspath(__file__))
FIXT = os.path.join(HERE, "fixtures", "profil_s3_1003")
PROGRESS_GOLDEN = os.path.join(HERE, "fixtures", "hw_progress_1525", "progress_golden.json")
GRID_GOLDEN = os.path.join(HERE, "fixtures", "hw_sim_1003", "grid_golden_1to8.json")


def _cards(*keys):
    """FitCards in the order given -- pass the LAUNCHER's card order (``order_cards``: the host card first)."""
    out = []
    for k in keys:
        c = HS.CATALOG[k]
        out.append(HF.FitCard(total_mib=c.total_mib, arch=c.sm, cls={"5090": "RTX5090", "3080-20G": "RTX3080"}.get(k, ""),
                              label=k))
    return out


def _nf():
    return HS.MODELS["NF"]


def _level(model_key, *keys, asm=None):
    m = HS.MODELS[model_key]
    prof = HF.load_profile(m.profile)
    if m.ckpt_mib is not None and m.weight_format != prof.weight_format:
        prof, _ = HF.with_checkpoint_mib(prof, m.ckpt_mib)
    return HF.evaluate(prof, _cards(*keys), argv=m.argv, asm=asm or HF.Assumptions(), records_profile=m.profile)


class CatalogEvidence(unittest.TestCase):
    def test_the_missing_cards_are_in_the_catalog_marked_borrowed(self):
        for key, total, sm in (("3070", 8192, "sm86"), ("5070", 12227, "sm120"), ("5070Ti", 16303, "sm120")):
            c = HS.CATALOG[key]
            self.assertEqual((c.total_mib, c.sm), (total, sm), key)
            self.assertTrue(c.borrowed, key)
            self.assertTrue(c.evidence.startswith("HW-BORROWED/unbelegt"), c.evidence)

    def test_rig_cards_are_metal_and_sm89_says_never_measured(self):
        self.assertEqual(HS.CATALOG["5090"].evidence, HS.EV_METAL)
        self.assertEqual(HS.CATALOG["3080-20G"].evidence, HS.EV_METAL)
        for key, c in HS.CATALOG.items():
            self.assertEqual("sm89 am Metall nie gemessen" in c.evidence, c.cc == (8, 9), key)
            self.assertEqual(c.borrowed, key in ("3070", "5070", "5070Ti"), key)

    def test_catalog_cli_prints_the_evidence(self):
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            self.assertEqual(HS.main(["--catalog"]), 0)
        out = buf.getvalue()
        self.assertIn("[HW-BORROWED/unbelegt", out)
        self.assertRegex(out, r"4090 .*\[NVML-RECORDING; sm89 am Metall nie gemessen\]")

    def test_seed_cards_carry_the_three_cards_as_borrowed(self):
        for name, total in (("RTX 3070", 8192), ("RTX 5070", 12227), ("RTX 5070 Ti", 16303)):
            spec = CL.seed_card("NVIDIA GeForce " + name)
            self.assertIsNotNone(spec, name)
            self.assertEqual((spec.total_mib, spec.source), (total, "borrowed"), name)
            self.assertIsNone(spec.gemm_tflops)           # nameplate peaks only, never a measurement
            self.assertIsNone(spec.membw_gbs)
        # the sm89 seeds stay plain seeds (test_card_library_sm89_seeds_1002)
        self.assertEqual(CL.seed_card("RTX 4090").source, "seed")
        # the name lookup of a sibling is not shadowed: 3070 is not 3080
        self.assertEqual(CL.seed_card("RTX 3080").total_mib, 10240)


class FitProfiles(unittest.TestCase):
    def test_the_data_files_are_the_derivation_of_the_config_fixtures(self):
        for prof, d in (("nextflash", "nextflash_int4mixed"), ("qwen27b", "qwen27b_int8_vocabembed")):
            derived = HF.derive_profile(os.path.join(FIXT, d, "config.json"), profile=prof)
            have = HF.load_profile(prof)
            a, b = msgspec.to_builtins(derived), msgspec.to_builtins(have)
            a.pop("derived_from"), b.pop("derived_from")
            self.assertEqual(a, b, prof)

    def test_nf_figures_equal_what_the_launcher_printed(self):
        p = HF.load_profile("nextflash")
        self.assertEqual((p.n_layers, p.attn_layers, p.n_experts), (48, 12, 512))
        self.assertAlmostEqual(p.disk_mib, 97719, delta=2)                         # "PLE 97719 MiB stays on disk"
        self.assertAlmostEqual(sum(p.layer_dense_mib), 3377, delta=3)              # 1520 A: dense 3377 MiB
        self.assertEqual(p.kv_bytes_per_token_per_attn_layer["fp8_e4m3"], 1088.0)  # "KV-PREIS 1088 B"
        self.assertTrue(p.is_moe)
        self.assertFalse(HF.load_profile("qwen27b").is_moe)

    def test_missing_profile_is_none_and_named(self):
        self.assertIsNone(HF.load_profile("no-such-profile"))
        m = dataclasses.replace(HS.MODELS["NF"], profile="no-such-profile")
        self.assertIsNone(HS.fit_of(m, []))

    def test_the_module_knows_no_model_name(self):
        path = HF.__file__
        tree = ast.parse(open(path).read())
        docs = {id(n.body[0].value) for n in ast.walk(tree)
                if isinstance(n, (ast.Module, ast.FunctionDef, ast.ClassDef))
                and n.body and isinstance(n.body[0], ast.Expr) and isinstance(getattr(n.body[0], "value", None), ast.Constant)}
        bad = re.compile(r"nextflash|qwen|\bNF\b|27B|gguf|nvfp4|int8", re.I)
        lits = [n.value for n in ast.walk(tree) if isinstance(n, ast.Constant) and isinstance(n.value, str)
                and id(n) not in docs and bad.search(n.value)]
        self.assertEqual(lits, [], "hw_fit must not branch on a model name; a profile is data")


class FitBound(unittest.TestCase):
    def test_nf_reference_fits_and_the_examples_follow_1520(self):
        self.assertEqual(_level("NF", "3080-20G", "5090", "3080-20G").level, HF.JA)   # order-independent input
        got = {k: _level("NF", *k.split("+")).level for k in (
            "3090+3090", "3090+3090+3090", "5090+3090+3090", "5090+5090", "3090+5070Ti", "4090+4090",
            "5090+3090+5070+3070", "3080-10G+3080-10G+3080-10G", "3070+3070+3070", "5070Ti+5070Ti+5070Ti")}
        self.assertEqual(got["3090+3090"], HF.JA)
        self.assertEqual(got["3090+3090+3090"], HF.JA)
        self.assertEqual(got["5090+3090+3090"], HF.JA)
        self.assertEqual(got["5090+5090"], HF.JA)
        self.assertEqual(got["3090+5070Ti"], HF.JA)
        self.assertEqual(got["4090+4090"], HF.JA)
        self.assertEqual(got["5090+3090+5070+3070"], HF.JA)
        self.assertEqual(got["3080-10G+3080-10G+3080-10G"], HF.NEIN)
        self.assertEqual(got["3070+3070+3070"], HF.NEIN)
        self.assertEqual(got["5070Ti+5070Ti+5070Ti"], HF.NEIN)

    def test_the_d_host_needs_17_3_gib_without_and_19_3_gib_with_mamba(self):
        """1520 A: the host rank needs >= 17,3 GiB (floor) .. 19,3 GiB (with the mamba slots)."""
        m = _nf()
        prof = HF.load_profile("nextflash")
        workers = _cards("3080-20G", "3080-20G")

        def level(host_total):
            host = HF.FitCard(total_mib=host_total, arch="sm120", cls="RTX5090", label="host")
            return HF.evaluate(prof, [host, *workers], argv=m.argv, records_profile="nextflash")

        floor = level(17600)       # 17671 needed without mamba
        self.assertEqual(floor.level, HF.NEIN)
        self.assertIn("D host", floor.first)
        self.assertIn("17671", floor.first)
        self.assertEqual(level(17700).level, HF.KNAPP)        # floor holds, 19805 with mamba does not
        self.assertEqual(level(19900).level, HF.JA)

    def test_27b_int8_fits_5090_plus_3080_but_not_3080_plus_3080(self):
        self.assertEqual(_level("27B-INT8", "5090", "3080-20G").level, HF.JA)
        v = _level("27B-INT8", "3080-20G", "3080-20G")
        self.assertEqual(v.level, HF.NEIN)
        self.assertIn("P stages hold", v.first)
        # the rig's other N=2 tests: NVFP4 and GGUF on 3080 + 3080
        self.assertEqual(_level("27B-NVFP4", "3080-20G", "3080-20G").level, HF.JA)
        self.assertEqual(_level("27B-GGUF", "3080-20G", "3080-20G").level, HF.JA)

    def test_a_synthetic_profile_needs_no_name(self):
        """A model that exists only as data: 8 dense layers, no records -> the bound runs, names the gaps."""
        p = HF.FitProfile(
            profile="synthetic-dense", weight_format="x", derived_from="test", n_layers=8,
            layer_families=("attn", "gdn") * 4, layer_dense_mib=(1000.0,) * 8, layer_expert_mib=(0.0,) * 8, n_experts=0,
            embed_mib=500.0, lm_head_mib=500.0, draft_mib=0.0, visual_mib=0.0, disk_mib=0.0,
            kv_bytes_per_token_per_attn_layer={"fp8_e4m3": 1024.0, "bf16": 2048.0},
            mamba_mib_per_slot_per_linear_layer=1.0)
        cards = [HF.FitCard(total_mib=12000, arch="sm86", cls="", label="a"),
                 HF.FitCard(total_mib=12000, arch="sm120", cls="", label="b")]
        v = HF.evaluate(p, cards, asm=HF.Assumptions(kv_tokens=1024))
        self.assertIn(v.level, (HF.JA, HF.KNAPP))
        self.assertTrue(any("no record" in m for m in v.marks), v.marks)
        self.assertTrue(any("HW-BORROWED" in m for m in v.marks), v.marks)      # residue borrowed by arch
        tiny = HF.evaluate(p, [HF.FitCard(total_mib=4000, arch="sm86", cls="", label="a")] * 2,
                           asm=HF.Assumptions(kv_tokens=1024))
        self.assertEqual(tiny.level, HF.NEIN)

    def test_a_flag_changes_the_verdict(self):
        """the knobs are arguments (CLI flags), not constants: fewer KV tokens let 3 x 5070 Ti hold the 27B INT8."""
        self.assertEqual(_level("27B-INT8", "5070Ti", "5070Ti", "5070Ti").level, HF.NEIN)
        self.assertEqual(_level("27B-INT8", "5070Ti", "5070Ti", "5070Ti", asm=HF.Assumptions(kv_tokens=32768)).level,
                         HF.JA)
        # a residue override moves a 3x3080-10G NF cell? no: it can not, 10 GiB < the stage fixed posts
        v = _level("NF", "3080-10G", "3080-10G", "3080-10G", asm=HF.Assumptions(residue_mib={"RTX3080": 0}))
        self.assertEqual(v.level, HF.NEIN)

    def test_dual_is_marked_not_modelled(self):
        cell = HS.simulate("3x3090", ["3090"] * 3, HS.MODELS["27B-NVFP4-DUAL"])
        self.assertTrue(any("NOT modelled" in m for m in cell.fit["marks"]), cell.fit["marks"])
        flip = HS.simulate("3x3090", ["3090"] * 3, HS.MODELS["27B-NVFP4"])
        self.assertFalse(any("NOT modelled" in m for m in flip.fit["marks"]))

    def test_the_fit_refusal_is_the_hw_sim_fit_blocker(self):
        c = HS.simulate("3x3070", ["3070"] * 3, HS.MODELS["NF"])
        self.assertIn("FIT", c.blockers)
        self.assertEqual(c.fit["level"], "nein")
        r = HS.simulate("ref", list(HS.REFERENCE_RIG), HS.MODELS["NF"])
        self.assertEqual((r.result, r.blockers), (HS.RUNS, []))
        self.assertEqual(r.fit["level"], "ja")


class PChunkModelOnlyUnderDynamic(unittest.TestCase):
    """The NF release runs ``--p-chunk-policy fixed`` (launcher default): the
    three-stage P-chunk table is never read, so a 4-card cell must not be
    refused P-CHUNK-MODEL (1520 A: a simulator artefact)."""

    KEYS = ["3080-20G", "5090", "3080-20G", "3080-20G"]

    def _blockers(self, policy):
        m = HS.MODELS["NF"]
        if policy:
            m = dataclasses.replace(m, argv=tuple(m.argv) + ("--p-chunk-policy", policy))
        # arm(True) exports FLLIPER_PDFLIP_FORCED_BOOT and nothing unsets it: patch the environment (as the 1518 test
        # does) or every later test of the process runs "forced"
        with mock.patch.dict(os.environ):
            refusals.arm(True)      # a --force boot: UNCALIBRATED is passed, the P-chunk stage is reached
            try:
                return HS.simulate("4x", self.KEYS, m).blockers
            finally:
                refusals.arm(False)

    def test_fixed_policy_has_no_p_chunk_blocker(self):
        self.assertNotIn("P-CHUNK-MODEL", self._blockers(None))
        self.assertNotIn("P-CHUNK-MODEL", self._blockers("fixed"))

    def test_dynamic_policy_still_checks_the_table(self):
        self.assertIn("P-CHUNK-MODEL", self._blockers("dynamic"))


class ProgressMeter(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.rows = HP.rows_for()
        cls.by = {f"{r.config} | {r.model}": r for r in cls.rows}

    def test_matrix_is_models_times_configurations(self):
        self.assertEqual(len(self.rows), len(HP.PROGRESS_MODELS) * len(HP.EXAMPLE_CONFIGS))
        labels = [c[0] for c in HP.EXAMPLE_CONFIGS]
        for want in ("2x3090", "3x3090", "4x3090", "2x5090", "5090+2x3090", "3070+5070+3090+5090", "2x4090",
                     "3x3080-10G", "3x3070", "3x5070Ti"):
            self.assertIn(want, labels)

    def test_equals_the_golden(self):
        with open(PROGRESS_GOLDEN) as fh:
            golden = json.load(fh)
        now = json.loads(json.dumps(HP.golden_of(self.rows)))
        self.assertEqual(sorted(now), sorted(golden))
        diff = [k for k in sorted(golden) if now[k] != golden[k]]
        self.assertEqual(diff, [], "cells moved (regenerate the golden if on purpose, see module doc): "
                         + "; ".join(f"{k}: {golden[k]} -> {now[k]}" for k in diff[:5]))

    def test_the_two_reference_rows_are_unchanged(self):
        """NF 5090 + 2x3080 (N=3) runs; the 27B reference (5090 + 3080, N=2) is refused only for the metal-proof state."""
        nf = self.by["REF 5090+2x3080 (N=3) | NF"]
        self.assertEqual((nf.fit, nf.result, nf.code, nf.blockers), ("ja", "läuft", "", []))
        r27 = self.by["REF 27B 5090+3080 (N=2) | 27B-INT8"]
        self.assertEqual((r27.fit, r27.result, r27.code, r27.blockers), ("ja", "verweigert", "HW-COUNT", ["METAL-UNPROVEN"]))
        # and the cell equals the pinned grid cell of 1003 (nothing moved by AP0)
        with open(GRID_GOLDEN) as fh:
            grid = json.load(fh)
        self.assertEqual(grid["rig --cards 1,0 (5090+3080) | 27B-INT8"], ["verweigert", "HW-COUNT", ["METAL-UNPROVEN"]])
        self.assertEqual(grid["3x ref 5090+3080 | NF"], ["läuft", "", []])

    def test_borrowed_cards_are_named_in_the_row(self):
        r = self.by["3070+5070+3090+5090 | NF"]
        self.assertTrue(any("3070: HW-BORROWED" in b for b in r.borrowed), r.borrowed)
        self.assertTrue(any("sm89" in b for b in self.by["2x4090 | NF"].borrowed))

    def test_missing_profile_prints_profil_fehlt(self):
        with mock.patch.object(HF, "load_profile", return_value=None):      # a model without a fit profile
            rows = HP.rows_for(("NF",), HP.EXAMPLE_CONFIGS[:1])
            self.assertEqual(rows[0].fit, "Profil fehlt")
            self.assertIn("Profil fehlt", HP.render(rows))

    def test_cli_prints_every_model_and_a_total(self):
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            self.assertEqual(HP.main(["--models", "NF,27B-GGUF", "--configs", "REF 5090+2x3080 (N=3),3x3070"]), 0)
        out = buf.getvalue()
        self.assertIn("FORTSCHRITT NF: passt rechnerisch 1/2, ohne Sperre (laeuft) 1/2", out)
        self.assertIn("FORTSCHRITT 27B-GGUF", out)
        self.assertIn("HW-PROGRESS cells=4", out)


if __name__ == "__main__":
    unittest.main()
