#!/usr/bin/env python
# Copyright 2026 SGLang Team
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# ==============================================================================
"""Generate a turnkey ``stack.toml`` from a captured argv/env pair.

The ship configuration on this rig is not the default of any script -- the
production defaults in ``route_a_631_prod_boot.sh`` have drifted from what
actually ran (different checkpoint, different per-rank MiB vector, different
pool, different stage ratio). The only authoritative description of the ship
config is a CAPTURE of the live process, taken from ``/proc/<pid>/cmdline``
and ``/proc/<pid>/environ`` before it was stopped.

So the config is GENERATED from that capture rather than retyped. Retyping a
40-flag launch line is how parity is lost, and parity is the acceptance
criterion for #539: the turnkey path must reproduce the ship config exactly,
or it is a different server that happens to start.

Two classes of captured value are dropped rather than pinned, and both are
identities of the dead boot rather than settings:

``SGLANG_PHASE_FLIP_INSTANCE``
    Its suffix is the pid of the captured process (``…-3940356``). Replaying
    it would stamp every future boot with a dead pid's rendezvous tag.

``SGLANG_BOOT_COMMIT``
    Provenance. It must be measured from the repo at boot, not asserted by a
    config file -- "which commit was that" is the first question asked of any
    measurement, and a pinned answer is a claim rather than an observation.

``PYTHONPATH`` is likewise NOT taken from the capture: the ship ran from
``/spinning/wt-631-routea/python``, a git worktree that an unrelated agent can
delete. The generated config roots the stack in the canonical checkout.

Usage:
    python scripts/turnkey_539_config_from_capture.py \
        --argv /spinning/evidence-631/s485/ship_argv.txt \
        --env  /spinning/evidence-631/s485/ship_env.txt \
        --out  deploy/turnkey/stack.rig3.toml
"""

from __future__ import annotations

import argparse
import os
import sys

#: Captured values that are identities of the captured boot, not settings.
DROP_ENV = {
    "SGLANG_PHASE_FLIP_INSTANCE",
    "SGLANG_BOOT_COMMIT",
    "PYTHONPATH",
    "CUDA_VISIBLE_DEVICES",   # derived from the card UUIDs at boot
}

#: Prefixes worth carrying into the config. Everything else in a captured
#: environ is the shell's, the agent's, or the container's -- inheriting it
#: would make the boot depend on who launched the capture.
KEEP_PREFIXES = ("SGLANG_", "HTSGLANG_", "PYTORCH_")
KEEP_EXACT = ("LD_LIBRARY_PATH",)


def read_argv(path: str):
    with open(path) as fh:
        return [a for a in fh.read().split("\n") if a != ""]


def read_env(path: str):
    out = {}
    with open(path) as fh:
        for line in fh:
            line = line.rstrip("\n")
            if "=" in line:
                k, v = line.split("=", 1)
                out[k] = v
    return out


def nvml_cards():
    """(uuid, name, total_mib) per card, NVML order. No CUDA context."""
    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "python"))
    from sglang.srt.registry import nvml

    return [(d.uuid, d.name, d.total_bytes // (1024 * 1024))
            for d in nvml.list_devices()]


def toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--argv", required=True)
    ap.add_argument("--env", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--repo", default="/spinning/htsglang-gpu")
    ap.add_argument("--lane", default="ship")
    ap.add_argument("--port", type=int, default=30030)
    a = ap.parse_args(argv)

    lane_argv = read_argv(a.argv)
    cap_env = read_env(a.env)
    cards = nvml_cards()

    # The capture's CUDA_VISIBLE_DEVICES gives the RANK ORDER, which is not
    # NVML order and must not be re-derived by guessing. We keep the capture's
    # order and list the cards in it.
    cvd = [u for u in cap_env.get("CUDA_VISIBLE_DEVICES", "").split(",") if u]
    by_uuid = {u: (u, n, t) for u, n, t in cards}
    missing = [u for u in cvd if u not in by_uuid]
    if missing:
        print(f"capture names cards this machine does not have: {missing}",
              file=sys.stderr)
        return 3
    ordered = [by_uuid[u] for u in cvd] if cvd else cards

    keep = {}
    for k, v in sorted(cap_env.items()):
        if k in DROP_ENV:
            continue
        if k.startswith(KEEP_PREFIXES) or k in KEEP_EXACT:
            keep[k] = v

    L = []
    W = L.append
    W("# GENERATED by scripts/turnkey_539_config_from_capture.py -- do not")
    W("# hand-edit the argv block; re-generate from a fresh capture instead.")
    W(f"# source argv: {a.argv}")
    W(f"# source env:  {a.env}")
    W("")
    W("[stack]")
    W('name = "rig3"')
    W(f"repo = {toml_str(a.repo)}")
    W(f'venv = {toml_str(os.path.join(a.repo, ".venv"))}')
    W('log_dir = "/var/log/htsglang"')
    W("# /spinning/htsglang-gpu is itself a worktree of /spinning/htsglang.")
    W("# Acknowledged deliberately rather than defaulted: it is the long-lived")
    W("# stack root (it holds the venv and the installed router unit already")
    W("# names it), unlike the ephemeral wt-* worktrees agents create and")
    W("# delete. A worktree whose gitdir has gone is still refused outright.")
    W("allow_worktree = true")
    W("")
    W("# Environment carried from the captured ship process. PYTHONPATH,")
    W("# CUDA_VISIBLE_DEVICES, SGLANG_PHASE_FLIP_INSTANCE and")
    W("# SGLANG_BOOT_COMMIT are deliberately absent: the first two are derived")
    W("# from [stack].repo and the card list, the last two are per-boot")
    W("# identities synthesized by the orchestrator.")
    W("[env]")
    for k, v in keep.items():
        W(f"{k} = {toml_str(v)}")
    W("")
    W("# Cards in RANK ORDER, taken from the capture's CUDA_VISIBLE_DEVICES.")
    W("# Addressed by UUID only: NVML index and CUDA ordinal are different")
    W("# orderings of the same hardware and both move across reboots.")
    for uuid, name, total in ordered:
        short = name.replace("NVIDIA GeForce ", "")
        W("[[cards]]")
        W(f"uuid = {toml_str(uuid)}")
        W(f"label = {toml_str(short)}")
        W(f"expect_name = {toml_str(short.split()[-1])}")
        W(f"# NVML total at generation time: {total} MiB")
        W("")
    W("[wheel]")
    W('# #384 wheel-shadow. Verified per docs/rig-runbook.md 2.1.')
    W('dist = "sglang-kernel"')
    W('version = "0.4.4"')
    W('must_import = ["sgl_kernel"]')
    W("")
    W("[plan]")
    W('# "pinned" once a plan is recorded with `turnkey plan-pin`. Until then')
    W('# "solve" is honest: it contributes no flags and says so, rather than')
    W("# refusing on a pin that was never written.")
    W('mode = "solve"')
    W('path = "/etc/htsglang/plan.ship.json"')
    W("")
    W("[preflight]")
    W("host_headroom_gib = 15")
    W("card_busy_mib = 512")
    W("")
    W("[preflight.disk_free_gib]")
    W('"/spinning" = 40')
    W("")
    W("[watchdog]")
    W("poll_s = 20")
    W("generation_probe_s = 120")
    W("# Reconciled with the server's own health budget: /health may take")
    W("# SGLANG_HEALTH_CHECK_TIMEOUT (default 20 s). The generation probe is")
    W("# a /generate call with its own explicit budget, well clear of it.")
    W("generation_timeout_s = 60")
    W("wedge_confirmations = 3")
    W("backoff_s = [30, 60, 120, 300, 600]")
    W("max_restarts = 5")
    W("restart_window_s = 3600")
    W("")
    W(f"[serving.{a.lane}]")
    W(f"port = {a.port}")
    W(f"cards = [{', '.join(str(i) for i in range(len(ordered)))}]")
    W(f'boot_log = "/var/log/htsglang/{a.lane}.boot.log"')
    W("# A cold JIT cache makes the first boot minutes long (#172/#615).")
    W("ready_timeout_s = 1800")
    W("argv = [")
    for tok in lane_argv:
        W(f"  {toml_str(tok)},")
    W("]")
    W("")

    text = "\n".join(L)
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    with open(a.out, "w") as fh:
        fh.write(text)
    print(f"wrote {a.out}  ({len(lane_argv)} argv tokens, {len(keep)} env "
          f"vars, {len(ordered)} cards)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
