#!/usr/bin/env bash
# #1348 mutant harness -- DANGER DIRECTION FIRST.
#
# The danger direction for a coverage instrument is NOT "it misses a line".
# It is "it reports a clean sweep it never measured": a reader who gets
# `0 unexecuted` from an absent trace closes the seam the instrument exists to
# open, and does it with more confidence than if there had been no instrument
# at all. Every mutant below therefore makes the tool QUIETER or MORE
# CONFIDENT, never noisier. Each must turn the file RED; the baseline must be
# GREEN before and after.
#
#   bash test/registered/unit/weg2/tools_mutants_1348.sh     # from the repo root
set -u
TEST=test/registered/unit/weg2/test_weg2_lane_coverage_1348.py
MOD=python/sglang/srt/weg2/lane_coverage.py
ING=scripts/weg2/lane_coverage_diff.py
LAU=python/sglang/srt/weg2/launcher.py
export CUDA_VISIBLE_DEVICES=""
export PYTHONPATH="$(pwd)/python"
PY=${PY:-python3}

WUP=python/sglang/srt/managers/scheduler_components/weight_updater.py
# RESTORED FROM A COPY, NEVER FROM GIT. `git checkout --` here would revert the
# WORKING TREE, i.e. destroy exactly the uncommitted work this harness is
# supposed to be testing. Copies, and a trap that runs on every exit path.
BAK=$(mktemp -d)
cp "$MOD" "$BAK/mod.py"; cp "$ING" "$BAK/ing.py"
cp "$LAU" "$BAK/lau.py"; cp "$WUP" "$BAK/wup.py"
restore() {
  cp "$BAK/mod.py" "$MOD"; cp "$BAK/ing.py" "$ING"
  cp "$BAK/lau.py" "$LAU"; cp "$BAK/wup.py" "$WUP"
}
trap 'restore; rm -rf "$BAK"' EXIT

run() {  # $1 = label, $2 = expectation (GREEN|RED), $3.. = pytest node args
  local label="$1" want="$2"; shift 2
  # The verdict is read off the ESCAPE-STRIPPED tail: a colour code between
  # "passed" and the comma once made a green baseline read as RED, which is a
  # harness lie in precisely the direction that hides a surviving mutant.
  out=$(timeout 900 "$PY" -m pytest "$@" -q -p no:randomly -p no:cacheprovider --color=no 2>&1 \
        | sed -r 's/\x1b\[[0-9;]*m//g' | tail -3)
  if echo "$out" | grep -qE "[0-9]+ (failed|error)"; then got=RED
  elif echo "$out" | grep -qE "[0-9]+ passed"; then got=GREEN
  else got=RED; fi
  printf '%-62s expected=%-5s got=%s\n' "$label" "$want" "$got"
  [ "$got" = "$want" ] || printf '    ^^ MUTANT SURVIVED / BASELINE BROKE\n%s\n' "$out"
}

# ==========================================================================
# THE HARNESS MUST BE ABLE TO FAIL. `patch` below REFUSES a mutation whose
# pattern does not match, instead of leaving the file untouched and letting
# `run` report GREEN as "mutant survived".
#
# THIS IS NOT HYPOTHETICAL -- it happened to this very file on 2026-09-12.
# The round-2 block was generated by a script that turned the `\n` inside its
# replacement patterns into REAL newlines, so every embedded snippet was a
# Python SyntaxError, every mutation was a silent no-op, and the harness
# reported EIGHT surviving mutants against code that kills all eight (checked
# by hand, one at a time). A harness that cannot tell "the mutant survived"
# from "the mutation never applied" is the same defect class as an ingest that
# cannot tell "nothing unexecuted" from "nothing observed -- which is the whole
# subject of the thing being tested.
# ==========================================================================
patch() {  # $1 = file, then a python snippet on stdin; refuses a no-op
  local f="$1"
  local before after
  before=$(md5sum < "$f")
  "$PY" - "$f" || { printf 'MUTATION FAILED TO RUN on %s\n' "$f"; return 1; }
  after=$(md5sum < "$f")
  if [ "$before" = "$after" ]; then
    printf '!! MUTATION-NOOP: %s is byte-identical after the patch -- the\n' "$f"
    printf '   pattern did not match. Any GREEN below is the HARNESS, not the code.\n'
    return 1
  fi
}

run "M0 baseline (unmutated)" GREEN "$TEST"

# --------------------------------------------------------------------------
# M1  THE TRACE FALLS SILENT AND THE INGEST REPORTS ZERO INSTEAD OF REFUSING.
#     The whole indicator law in one mutation: a module absent from the dump
#     is treated as a module with nothing unexecuted.
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace(
    '        if entry is None:\n'
    '            rep.no_observation(rel, rank, group, "module-absent-from-dump")\n'
    '            continue\n',
    '        if entry is None:\n'
    '            rep.say(f"WEG2-COVERAGE UNEXECUTED module={rel} rank={rank} "\n'
    '                    f"lines=[] executed_pct=100.0")  # M1\n'
    '            continue\n', 1)
open(p, 'w').write(s)
EOF
run "M1 absent module reported as 0 unexecuted" RED "$TEST::NoObservationIsNeverZero"

# --------------------------------------------------------------------------
# M2  THE COUNT CHECK IS DISABLED. A line the tracer recorded that is not in
#     the source at all (drift, a wrong root, a stale dump) is silently kept,
#     and the difference of two incompatible denominators is printed as a
#     finding.
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace(
    '        stray = [n for n in raw if n < 1 or n > n_source_lines]\n',
    '        stray = []  # M2\n', 1)
open(p, 'w').write(s)
EOF
run "M2 tally check disabled (stray lines accepted)" RED \
    "$TEST::TheIngestPrintsUnexecutedLines::test_the_tally_holds_or_the_ingest_refuses"

# --------------------------------------------------------------------------
# M3  AN ALLOWLISTED MODULE DROPS OUT OF THE ALLOWLIST. The report then looks
#     complete and is missing a whole module of the lane -- the failure mode a
#     hand-maintained scope list has by construction.
restore
patch "$MOD" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('    "python/sglang/srt/weg2/weight_exchange_shadow.py",\n', '', 1)  # M3
open(p, 'w').write(s)
EOF
run "M3 allowlist loses weight_exchange_shadow" RED \
    "$TEST::TheAllowlistNamesFilesThatExist"

# --------------------------------------------------------------------------
# M4  THE OFF STATE STOPS BEING BYTE-IDENTICAL: arm() falls back to a
#     directory of its own instead of returning, so an unarmed acceptance boot
#     silently pays coverage.py's line tracer.
restore
patch "$MOD" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace(
    '    directory = directory or os.environ.get(DIR_ENV) or ""\n'
    '    if not directory:\n'
    '        return False\n',
    '    directory = directory or os.environ.get(DIR_ENV) or "/tmp/m4"  # M4\n', 1)
open(p, 'w').write(s)
EOF
run "M4 arm falls back to a directory instead of staying off" RED \
    "$TEST::OffIsByteIdentical"

# --------------------------------------------------------------------------
# M5  SOURCE DRIFT IS IGNORED. The dump is read against a different checkout
#     and every line number is confidently wrong.
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('        if dump_sha != tree_sha:\n',
              '        if False:  # M5\n', 1)
open(p, 'w').write(s)
EOF
run "M5 source-drift check removed" RED \
    "$TEST::TheIngestPrintsUnexecutedLines::test_source_drift_between_boot_and_ingest_refuses"

# --------------------------------------------------------------------------
# M6  THE LAUNCHER STOPS POPPING THE VARIABLE. A value inherited from the
#     operator's shell then arms the tracer on a boot that never asked, which
#     is exactly the ambient-variable property this flag exists to avoid.
restore
patch "$LAU" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('        env.pop("SGLANG_WEG2_LANE_COVERAGE_DIR", None)\n',
              '        pass  # M6\n', 1)
open(p, 'w').write(s)
EOF
run "M6 launcher no longer pops the variable when OFF" RED \
    "$TEST::TheLauncherFlagIsOffByDefault::test_build_env_pops_the_variable_when_the_flag_is_off"

# --------------------------------------------------------------------------
# M7  THE LEG HOOK IS UNWIRED. Present-but-unwired (#859) is the expensive
#     middle state: the module imports, its tests are green, and nothing on
#     the product path ever calls it.
restore
patch "$WUP" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('                wlc.note_leg_end(hook)\n', '                pass  # M7\n', 1)
open(p, 'w').write(s)
EOF
run "M7 leg hook no longer calls the instrument" RED \
    "$TEST::TheWiringPinsAreAstNotSubstring"
    "$TEST::TheWiringPinsAreAstNotSubstring"


# ==========================================================================
# ROUND 2 -- the mutants the adversarial review of 2026-09-12 wrote (MR1-MR4,
# all of which survived round 1's 21 tests) plus one per MUST_FIX (MR5-MR8).
# Same direction throughout: the tool goes quieter, never noisier.
# ==========================================================================

# MR1  EQUIVALENT MUTANT, PROVEN, NOT A SURVIVOR -- and recorded rather than
#      quietly dropped, because "we removed the mutant that lived" is how a
#      mutation table becomes decoration.
#
#      The reviewer's MR1 was "an empty dump directory prints NOTHING". That
#      defect is CLOSED, but not by the line MR1 deletes: with an expectation
#      list every absent (group, rank) is named by `emit_missing_pairs`, and
#      WITHOUT one the `no-expectation-list` refusal fires first. Measured on
#      an empty directory with `--expect P=2,D=1`: three
#      `reason=rank-wrote-no-dump` lines and a non-zero exit, with or without
#      the `no-dump-files-in` line. So deleting it changes no observable
#      behaviour -- it is an equivalent mutant, and no test can or should kill
#      it. The line stays because it names the DIRECTORY, which the per-rank
#      lines do not.
#
#      MR9 below is the mutant that MR1 was reaching for: the guarantee is not
#      "this one line exists", it is "an empty directory can never be read as
#      a clean sweep, by a person or by `$?`".

# MR9  A MISSING EXPECTED RANK NO LONGER ESCALATES THE EXIT CODE (review N-1):
#      a caller reading only `$?` reads green over a boot where nothing was
#      observed at all.
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('            rep.rc = max(rep.rc, 1)\n', '            pass  # MR9\n', 1)
open(p, 'w').write(s)
EOF
run "MR9 missing expected rank does not fail the exit code" RED \
    "$TEST::AMissingExpectedRankEscalatesTheExitCode"

# MR2  MODULES IMPORTED BEFORE THE ARM REPORT 100 % EXECUTED. The "obvious
#      fix" for the 23.7 % artefact, and it erases the whole reading list.
#      Survived round 1 because not one of its 21 tests ever set the flag.
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('        executed = translated & executable\n',
              '        executed = set(executable) if entry.get("imported_before_arm") else (translated & executable)  # MR2\n', 1)
open(p, 'w').write(s)
EOF
run "MR2 imported_before_arm modules report 100% executed" RED \
    "$TEST::TheArtefactLinesAreNamedNotMixedIn"

# MR3  A MODULE WITH ZERO RECORDED LINES FALLS THROUGH SILENTLY.
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
old = '        if not raw:\n            rep.no_observation(rel, rank, group, "no-lines-recorded")\n            continue\n'
s = s.replace(old, '        if not raw:\n            continue  # MR3\n', 1)
open(p, 'w').write(s)
EOF
run "MR3 module with zero recorded lines stays silent" RED \
    "$TEST::AModuleWithNoRecordedLinesRefuses"

# MR4  THE LEG HOOK IS COMMENTED OUT AND THE TOKEN STAYS IN THE SOURCE
#      (#1341 class). Round 1's wiring tests were substring greps, so the
#      comment satisfied them and the instrument was unwired with every test
#      green. The pins are AST-based now: a comment is not in the tree.
restore
patch "$WUP" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('                wlc.note_leg_end(hook)\n',
              '                pass  # MR4: wlc.note_leg_end(hook)\n', 1)
open(p, 'w').write(s)
EOF
run "MR4 leg hook commented out, token still in source" RED \
    "$TEST::TheWiringPinsAreAstNotSubstring"

# MR5  THE BOOT TOKEN IS NOT CHECKED -- yesterday's dump is read as today's.
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('    if dump_token != boot_token:\n', '    if False:  # MR5\n', 1)
open(p, 'w').write(s)
EOF
run "MR5 stale dump from another boot is accepted" RED \
    "$TEST::MF2_AStaleDumpIsNeverReadAsThisBoot"

# MR6  A MISSING EXPECTED RANK IS NOT NAMED -- the original MF-1 defect.
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('def emit_missing_pairs(rep: Report) -> None:\n',
              'def emit_missing_pairs(rep: Report) -> None:\n    return  # MR6\n', 1)
open(p, 'w').write(s)
EOF
run "MR6 an expected rank that wrote no dump is not named" RED \
    "$TEST::MF1_AnExpectedRankThatWroteNoDumpIsNamed"

# MR7  THE TRACER IS LEFT RUNNING PAST THE LEG END (the MF-4 defect restored):
#      every timing of the rest of the boot is confounded at up to 4x.
restore
patch "$MOD" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('    _cov.stop()\n', '    pass  # MR7\n', 1)
open(p, 'w').write(s)
EOF
run "MR7 tracer left running past the leg end" RED \
    "$TEST::MF4_TheTracerRunsOnlyInsideTheLegBracket"

# MR8  AN EMPTY sha256 IS TREATED AS "NO DRIFT" (the MF-3 defect restored).
restore
patch "$ING" <<'EOF'
import sys
p = sys.argv[1]; s = open(p).read()
s = s.replace('        if not dump_sha:\n', '        if False:  # MR8\n', 1)
open(p, 'w').write(s)
EOF
run "MR8 empty sha silently disables the source guard" RED \
    "$TEST::MF3_AnEmptyShaIsARefusalNotASkip"

restore
run "M9 baseline again (all mutations reverted)" GREEN "$TEST"
