#!/usr/bin/env bash
# Re-generate the "local model" Claude Code agent entry from the RUNNING
# htsglang server. This is the mechanism that makes the entry follow a model
# switch: nothing about the checkpoint is hardcoded -- the id, the context
# length and the residency come out of GET /v1/models on the live server.
#
# Run it after every serving switch (INT8 -> NVFP4 -> GGUF -> whatever):
#
#   scripts/dev/register_local_model.sh                     # default endpoint
#   scripts/dev/register_local_model.sh -b http://127.0.0.1:30030
#   scripts/dev/register_local_model.sh --agent-dir /path/to/.claude/agents
#
# Writes:
#   <agent-dir>/local-model.md                      the agent definition
#   ~/.config/htsglang/local_model_agent.env        defaults for the wrapper
#
# The agent definition is a NAMED FALLBACK, and the file says so in its own
# body: Claude Code cannot bind a subagent's own inference to a foreign
# endpoint (no baseUrl/provider/env key in the subagent frontmatter schema;
# every ANTHROPIC_*_BASE_URL is process-global). The agent therefore drives
# the local model through scripts/dev/local_model_agent.sh, which starts a
# separate `claude` process with a process-scoped environment.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BASE_URL="http://127.0.0.1:30030"
AGENT_DIR="$REPO_ROOT/.claude/agents"
CONF_DIR="$HOME/.config/htsglang"
MAX_TOKENS=4096

while [[ $# -gt 0 ]]; do
    case "$1" in
        -b|--base-url)   BASE_URL="$2"; shift 2 ;;
        --agent-dir)     AGENT_DIR="$2"; shift 2 ;;
        --conf-dir)      CONF_DIR="$2"; shift 2 ;;
        -t|--max-tokens) MAX_TOKENS="$2"; shift 2 ;;
        -h|--help)       sed -n '1,25p' "$0"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

echo "register_local_model: querying $BASE_URL/v1/models"
MODELS_JSON="$(curl -sS -m 15 "$BASE_URL/v1/models")"

read -r MODEL_ID CTX_LEN RESIDENCY < <(
    printf '%s' "$MODELS_JSON" | python3 -c '
import json, sys
d = json.load(sys.stdin)
entries = d.get("data") or []
if not entries:
    sys.exit("register_local_model: server reported no models")
m = entries[0]
x = m.get("x-htsglang") or {}
print(m["id"], m.get("max_model_len", "unknown"), x.get("residency", "unknown"))
'
)

# The Anthropic Messages front is what a Claude Code process needs. Probe it
# rather than assume it: a boot that does not expose it cannot back an agent,
# and finding that out here beats finding it out inside an agent run.
MSG_CODE="$(curl -sS -m 20 -o /dev/null -w '%{http_code}' \
    -X POST "$BASE_URL/v1/messages" \
    -H 'content-type: application/json' \
    -H 'anthropic-version: 2023-06-01' \
    -d '{"model":"probe","max_tokens":8,"messages":[{"role":"user","content":"hi"}]}' || echo 000)"
if [[ "$MSG_CODE" != "200" ]]; then
    echo "register_local_model: POST /v1/messages returned HTTP $MSG_CODE" >&2
    echo "  the local-model agent needs the Anthropic Messages front; refusing" >&2
    echo "  to write a config that points at an endpoint which cannot serve it." >&2
    exit 4
fi

# A boot WITHOUT --reasoning-parser leaks raw </think> markers into the answer
# and refuses Anthropic `thinking` blocks outright. The wrapper suppresses the
# request; report the state so the operator can fix the boot recipe instead.
REASONING="unknown"
if printf '%s' "$MODELS_JSON" | grep -q '"reasoning'; then
    REASONING="advertised"
fi

mkdir -p "$AGENT_DIR" "$CONF_DIR"

cat > "$CONF_DIR/local_model_agent.env" <<EOF
# Generated by scripts/dev/register_local_model.sh -- do not edit by hand.
# Regenerate after every serving switch; nothing here is a hand-picked value.
# Source server: $BASE_URL
# Generated:     $(date -u +%Y-%m-%dT%H:%M:%SZ)
LOCAL_MODEL_BASE_URL=$BASE_URL
LOCAL_MODEL_ID=$MODEL_ID
LOCAL_MODEL_MAX_OUTPUT_TOKENS=$MAX_TOKENS
LOCAL_MODEL_CONTEXT_LENGTH=$CTX_LEN
LOCAL_MODEL_AUTH_TOKEN=local-no-auth
LOCAL_MODEL_TIMEOUT=600
LOCAL_MODEL_ALLOWED_TOOLS=
EOF

SHORT_NAME="$(basename "$MODEL_ID")"

cat > "$AGENT_DIR/local-model.md" <<EOF
---
name: local-model
description: Runs a prompt on the LOCAL htsglang server ($SHORT_NAME) instead of the Anthropic API. Use for bulk/cheap/offline reasoning that should not leave the rig, for dogfooding the served checkpoint, and for any determined-answer probe against the live serving instance.
tools: Bash, Read, Grep, Glob
model: haiku
---

Generated by \`scripts/dev/register_local_model.sh\` from the live server at
$BASE_URL on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not hand-edit: re-run the
script after a serving switch and this file follows the new checkpoint.

Currently served:

| field | value |
|---|---|
| model id | \`$MODEL_ID\` |
| endpoint | $BASE_URL |
| max_model_len | $CTX_LEN |
| residency | $RESIDENCY |
| Anthropic Messages front | present (HTTP $MSG_CODE on POST /v1/messages) |
| reasoning parser advertised | $REASONING |

## What you are

You are a THIN DRIVER. Your own inference does not run on the local model and
cannot be made to: Claude Code has no per-subagent endpoint binding. The
subagent frontmatter schema is closed
(\`name/description/tools/disallowedTools/model/permissionMode/maxTurns/skills/
mcpServers/hooks/memory/background/effort/isolation/color/initialPrompt\`) and
carries no \`baseUrl\`/\`provider\`/\`env\` key; \`CLAUDE_CODE_SUBAGENT_MODEL\` only
remaps the model NAME on the endpoint the session already uses; and every
\`ANTHROPIC_*_BASE_URL\` is a process-global environment variable, so setting
one in \`settings.json\` would reroute the PARENT session too. This agent is the
named fallback for that gap, not a workaround pretending to be the feature.

The real local-model inference happens in a SEPARATE \`claude\` process that
this agent starts, with a process-scoped environment. That process is a full
Claude Code agent loop -- it is not a single completion call.

## How to run the local model

\`\`\`bash
$REPO_ROOT/scripts/dev/local_model_agent.sh -- "<your prompt>"
\`\`\`

Options: \`-b BASE_URL\`, \`-m MODEL\`, \`-t MAX_OUTPUT_TOKENS\`, \`-T TIMEOUT_SECONDS\`,
\`--allow-tools "Read,Grep"\` (default: no tools, pure reasoning).

Rules:
- Always pass a bounded \`-T\`; never wait unbounded on the rig.
- Quote the local model's answer VERBATIM in your report and name the model id
  you got it from. A success message is not evidence -- the answer text is.
- If the wrapper fails, report the exact HTTP status/stderr. Do not fall back
  to answering from your own model and present it as the local model's answer.
- For a raw single-shot completion without an agent loop, call the endpoint
  directly instead:
  \`curl -sS $BASE_URL/v1/messages -H 'content-type: application/json' -H 'anthropic-version: 2023-06-01' -d '{"model":"$MODEL_ID","max_tokens":256,"messages":[{"role":"user","content":"..."}]}'\`
EOF

echo "register_local_model: wrote $AGENT_DIR/local-model.md"
echo "register_local_model: wrote $CONF_DIR/local_model_agent.env"
echo "register_local_model: model=$MODEL_ID ctx=$CTX_LEN residency=$RESIDENCY reasoning=$REASONING"
