"""efeu-TP14: gfx1103 build of sgl-kernel's EAGLE/NEXTN tree ops vs the
serving tree's Triton implementations (the reference the laptop ran on).

  * upstream fixed case (sgl-kernel/tests/speculative/test_eagle_utils.py)
  * differential, randomized drafts generated by the serving tree's own
    select_top_k_tokens -> organize_draft_results pipeline:
      build_tree_kernel_efficient : native == Triton (tree_mask, positions,
                                    retrive_index/next_token/next_sibling)
      verify_tree_greedy          : native == Triton (predicts, accept_index,
                                    accept_token_num) on random target_predict
    for chain drafts (topk=1, steps 1..3) and trees (topk 2..4, steps 2..3),
    bs 1..4, FULL_MASK.
  * red without the op: test_native_ops_present fails when sgl_spec_rocm
    cannot be imported.
Run on the laptop (HSA_OVERRIDE_GFX_VERSION=11.0.0), PYTHONPATH = build dir +
serving tree python.
"""

import itertools

import pytest
import torch

DEV = "cuda"


def _native():
    import sgl_spec_rocm

    return sgl_spec_rocm


def test_native_ops_present():
    m = _native()
    assert hasattr(torch.ops.sgl_spec_rocm, "verify_tree_greedy")
    assert hasattr(torch.ops.sgl_spec_rocm, "build_tree_kernel_efficient")
    assert callable(m.verify_tree_greedy) and callable(m.build_tree_kernel_efficient)


def test_verify_tree_greedy_upstream_case():
    m = _native()
    t = lambda x, dt=torch.int64: torch.tensor(x, dtype=dt, device=DEV)  # noqa: E731
    candidates = t([[0, 1, 2, 3, 4, 5], [7, 8, 9, 10, 11, 12]])
    retrive_index = t([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]])
    retrive_next_token = t([[1, 2, -1, 4, 5, -1], [4, 2, 3, -1, 5, -1]])
    retrive_next_sibling = t([[-1, 3, -1, -1, -1, -1], [-1, -1, -1, -1, 1, -1]])
    logits = torch.full((2, 6, 20), 1, dtype=torch.float32, device=DEV)
    logits[0, 0, 3] = logits[0, 3, 4] = logits[0, 4, 5] = 10
    logits[1, 0, 11] = logits[1, 4, 12] = 10
    for i in range(2):
        for j in range(6):
            if torch.max(logits[i][j]) < 10:
                logits[i][j][18] = 10
    target_predict = torch.argmax(logits, dim=-1)
    predicts = torch.full((12,), -1, dtype=torch.int32, device=DEV)
    accept_index = torch.full((2, 4), -1, dtype=torch.int32, device=DEV)
    accept_token_num = torch.zeros((2,), dtype=torch.int32, device=DEV)
    m.verify_tree_greedy(
        predicts=predicts, accept_index=accept_index, accept_token_num=accept_token_num,
        candidates=candidates, retrive_index=retrive_index,
        retrive_next_token=retrive_next_token, retrive_next_sibling=retrive_next_sibling,
        target_predict=target_predict,
    )
    assert predicts.tolist() == [3, -1, -1, 4, 5, 18, 11, -1, -1, -1, 12, 18]
    assert accept_index.tolist() == [[0, 3, 4, 5], [6, 10, 11, -1]]
    assert accept_token_num.tolist() == [3, 2]


def _draft(bs, topk, steps, vocab, gen):
    from sglang.srt.speculative.eagle_utils import organize_draft_results
    from sglang.srt.speculative.spec_utils import select_top_k_tokens

    score_list, token_list, parents_list = [], [], []
    scores = None
    for i in range(steps):
        rows = bs if i == 0 else bs * topk
        logits = torch.randn((rows, vocab), generator=gen, device="cpu").to(DEV)
        p = torch.softmax(logits, dim=-1)
        topk_p, topk_index = torch.topk(p, topk, dim=-1)
        _, _, scores, (s, tk, par) = select_top_k_tokens(i, topk_p, topk_index, None, scores, topk)
        score_list.append(s)
        token_list.append(tk)
        parents_list.append(par)
    num_draft = min(topk * steps + 1, 1 + sum(t.shape[1] for t in token_list))
    parent_list, top_idx, draft_tokens = organize_draft_results(
        score_list, token_list, parents_list, num_draft
    )
    return parent_list, top_idx, draft_tokens, num_draft


def _build(fn, parent_list, top_idx, seq_lens, topk, steps, num_draft):
    bs = seq_lens.numel()
    tree_mask = torch.full(
        (int(seq_lens.sum()) * num_draft + num_draft * num_draft * bs,), True, device=DEV
    )
    retrieve = torch.full((3, bs, num_draft), -1, device=DEV, dtype=torch.long)
    positions = torch.empty((bs * num_draft,), device=DEV, dtype=torch.long)
    fn(parent_list, top_idx, seq_lens, tree_mask, positions,
       retrieve[0], retrieve[1], retrieve[2], topk, steps, num_draft, 0)
    torch.cuda.synchronize()
    return tree_mask, positions, retrieve


CASES = [(1, s) for s in (1, 2, 3)] + [(k, s) for k in (2, 3, 4) for s in (2, 3)]


@pytest.mark.parametrize("topk,steps", CASES)
@pytest.mark.parametrize("bs", [1, 2, 4])
def test_build_and_verify_match_triton(topk, steps, bs):
    from sglang.srt.speculative.eagle_utils import (
        sgl_build_tree_kernel_triton,
        verify_tree_greedy_triton,
    )

    m = _native()
    gen = torch.Generator().manual_seed(1000 * topk + 10 * steps + bs)
    vocab = 64
    parent_list, top_idx, draft_tokens, num_draft = _draft(bs, topk, steps, vocab, gen)
    seq_lens = torch.randint(5, 40, (bs,), generator=gen).to(DEV)

    nat = _build(m.build_tree_kernel_efficient, parent_list, top_idx, seq_lens, topk, steps, num_draft)
    tri = _build(sgl_build_tree_kernel_triton, parent_list, top_idx, seq_lens, topk, steps, num_draft)
    for a, b, name in zip(nat, tri, ("tree_mask", "positions", "retrieve")):
        assert torch.equal(a, b), f"build_tree {name} differs (topk={topk} steps={steps} bs={bs})"

    _, _, retrieve = nat
    bonus = torch.randint(0, vocab, (bs,), generator=gen).to(DEV)
    candidates = torch.cat((bonus.unsqueeze(1), draft_tokens), dim=1)
    for trial in range(4):
        # target agrees with the draft with probability ~1/2 per position
        tp = torch.where(
            torch.rand(candidates.shape, generator=gen).to(DEV) < 0.5,
            torch.roll(candidates, -1, dims=1),
            torch.randint(0, vocab, candidates.shape, generator=gen).to(DEV),
        )
        outs = []
        for fn, kw in ((m.verify_tree_greedy, "retrive"), (verify_tree_greedy_triton, "retrieve")):
            predicts = torch.full((bs * num_draft,), -1, dtype=torch.int32, device=DEV)
            accept_index = torch.full((bs, steps + 1), -1, dtype=torch.int32, device=DEV)
            accept_num = torch.zeros((bs,), dtype=torch.int32, device=DEV)
            fn(predicts=predicts, accept_index=accept_index, accept_token_num=accept_num,
               candidates=candidates, target_predict=tp,
               **{f"{kw}_index": retrieve[0], f"{kw}_next_token": retrieve[1],
                  f"{kw}_next_sibling": retrieve[2]})
            torch.cuda.synchronize()
            outs.append((predicts.clone(), accept_index.clone(), accept_num.clone()))
        for a, b, name in zip(outs[0], outs[1], ("predicts", "accept_index", "accept_token_num")):
            assert torch.equal(a, b), f"verify {name} differs (topk={topk} steps={steps} bs={bs} trial={trial})"
